/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.views;

import java.text.ParseException;
import javax.swing.JPanel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author BiGDoGKD
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        setSize(900,520);
        setResizable(false);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLayer = new javax.swing.JLayeredPane();
        searchCustomerPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        addCustomerTitlePanel1 = new javax.swing.JPanel();
        addCustomerTitle1 = new javax.swing.JLabel();
        customerDetailsFormPanel1 = new javax.swing.JPanel();
        cusSearchInputPanel = new javax.swing.JPanel();
        enterMobileNoLabel = new javax.swing.JLabel();
        cusMobileInput = new javax.swing.JTextField();
        cusSearchBtnPanel = new javax.swing.JPanel();
        searchCustomerBtn = new javax.swing.JButton();
        addCusBtnPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cusIDSearchResult = new javax.swing.JLabel();
        cusIDLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        cusNameSearchResult = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        cusAddressSearchResult = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        cusPointsSearchResult = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        clearDetailsPanel = new javax.swing.JPanel();
        clearInfoBtn = new javax.swing.JButton();
        addCashierPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        addCashierTitlePanel = new javax.swing.JPanel();
        addCashierTitle = new javax.swing.JLabel();
        cashierDetailsFormPanel = new javax.swing.JPanel();
        cashNamePanel = new javax.swing.JPanel();
        cashNameLabel = new javax.swing.JLabel();
        cashName = new javax.swing.JTextField();
        addressPanel = new javax.swing.JPanel();
        addressLabel = new javax.swing.JLabel();
        cashAddress = new javax.swing.JTextField();
        usernamePanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        cashUsername = new javax.swing.JTextField();
        passwordPanel = new javax.swing.JPanel();
        passwordLabel = new javax.swing.JLabel();
        cashPassword = new javax.swing.JTextField();
        cashNamePanel1 = new javax.swing.JPanel();
        cashMobileLabel = new javax.swing.JLabel();
        cashMobile = new javax.swing.JTextField();
        addCashBtnPanel = new javax.swing.JPanel();
        addCashierBtn = new javax.swing.JButton();
        viewCashiersPanel = new javax.swing.JPanel();
        viewCashiersTitlePanel = new javax.swing.JPanel();
        viewCashiersTitle = new javax.swing.JLabel();
        cashiersTablePanel = new javax.swing.JPanel();
        cashiersInfoTablePanel = new javax.swing.JScrollPane();
        cashiersInfoTable = new javax.swing.JTable();
        addProductPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        addProductTitlePanel = new javax.swing.JPanel();
        addProductTitle = new javax.swing.JLabel();
        productDetailsFormPanel = new javax.swing.JPanel();
        productNamePanel = new javax.swing.JPanel();
        productNameLabel = new javax.swing.JLabel();
        productName = new javax.swing.JTextField();
        productPricePanel = new javax.swing.JPanel();
        productPriceLabel = new javax.swing.JLabel();
        productPrice = new javax.swing.JTextField();
        addProductBtnPanel = new javax.swing.JPanel();
        addProductBtn = new javax.swing.JButton();
        viewProductsPanel = new javax.swing.JPanel();
        viewProductsTitlePanel = new javax.swing.JPanel();
        viewCashiersTitle1 = new javax.swing.JLabel();
        cashiersTablePanel1 = new javax.swing.JPanel();
        cashiersInfoTablePanel1 = new javax.swing.JScrollPane();
        cashiersInfoTable1 = new javax.swing.JTable();
        settingsPanel = new javax.swing.JPanel();
        left = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        adminMobile = new javax.swing.JLabel();
        adminName = new javax.swing.JLabel();
        adminAddress = new javax.swing.JLabel();
        right = new javax.swing.JPanel();
        rightTopPanel = new javax.swing.JPanel();
        myNamePanel = new javax.swing.JPanel();
        myNameLabel = new javax.swing.JLabel();
        myName = new javax.swing.JTextField();
        myAddressPanel = new javax.swing.JPanel();
        myAddressLabel = new javax.swing.JLabel();
        myAddress = new javax.swing.JTextField();
        myMobilePanel = new javax.swing.JPanel();
        myMobileLabel = new javax.swing.JLabel();
        myMobile = new javax.swing.JTextField();
        myInfoActionPanel = new javax.swing.JPanel();
        saveChangesBtn = new javax.swing.JButton();
        cancelChangesBtn = new javax.swing.JButton();
        rightBottomPanel = new javax.swing.JPanel();
        currentPasswordPanel = new javax.swing.JPanel();
        currPasswordLabel = new javax.swing.JLabel();
        currPassword = new javax.swing.JPasswordField();
        newPasswordPanel = new javax.swing.JPanel();
        newPasswordLabel = new javax.swing.JLabel();
        newPassword = new javax.swing.JPasswordField();
        confPasswordPanel = new javax.swing.JPanel();
        confPasswordLabel = new javax.swing.JLabel();
        confPassword = new javax.swing.JPasswordField();
        myPasswordActionPanel = new javax.swing.JPanel();
        saveNewPasswordBtn = new javax.swing.JButton();
        cancelPasswordChangeBtn = new javax.swing.JButton();
        viewCustomersPanel = new javax.swing.JPanel();
        viewCustomersTitlePanel = new javax.swing.JPanel();
        viewCustomersTitle = new javax.swing.JLabel();
        customersTablePanel = new javax.swing.JPanel();
        customersInfoTablePanel = new javax.swing.JScrollPane();
        customersInfoTable = new javax.swing.JTable();
        viewSalesPanel = new javax.swing.JPanel();
        salesPanel = new javax.swing.JPanel();
        orderDetailsTitlePanel = new javax.swing.JPanel();
        orderSecTitle = new javax.swing.JLabel();
        salesTablePanel = new javax.swing.JPanel();
        orderDetailsTablePanel = new javax.swing.JScrollPane();
        orderDetailsTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLayer.setMaximumSize(new java.awt.Dimension(900, 500));
        panelLayer.setPreferredSize(new java.awt.Dimension(900, 500));
        panelLayer.setLayout(new java.awt.CardLayout());

        searchCustomerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addCustomerTitlePanel1.setPreferredSize(new java.awt.Dimension(440, 50));

        addCustomerTitle1.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        addCustomerTitle1.setText("Search Customer");

        javax.swing.GroupLayout addCustomerTitlePanel1Layout = new javax.swing.GroupLayout(addCustomerTitlePanel1);
        addCustomerTitlePanel1.setLayout(addCustomerTitlePanel1Layout);
        addCustomerTitlePanel1Layout.setHorizontalGroup(
            addCustomerTitlePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCustomerTitlePanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(addCustomerTitle1)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        addCustomerTitlePanel1Layout.setVerticalGroup(
            addCustomerTitlePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCustomerTitlePanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(addCustomerTitle1)
                .addContainerGap())
        );

        jPanel3.add(addCustomerTitlePanel1);

        customerDetailsFormPanel1.setPreferredSize(new java.awt.Dimension(440, 280));

        enterMobileNoLabel.setText("Enter Customer Mobile No.");

        cusMobileInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cusMobileInputKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout cusSearchInputPanelLayout = new javax.swing.GroupLayout(cusSearchInputPanel);
        cusSearchInputPanel.setLayout(cusSearchInputPanelLayout);
        cusSearchInputPanelLayout.setHorizontalGroup(
            cusSearchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cusSearchInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cusSearchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterMobileNoLabel)
                    .addComponent(cusMobileInput, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        cusSearchInputPanelLayout.setVerticalGroup(
            cusSearchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cusSearchInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterMobileNoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cusMobileInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        customerDetailsFormPanel1.add(cusSearchInputPanel);

        searchCustomerBtn.setText("Search Customer");

        javax.swing.GroupLayout cusSearchBtnPanelLayout = new javax.swing.GroupLayout(cusSearchBtnPanel);
        cusSearchBtnPanel.setLayout(cusSearchBtnPanelLayout);
        cusSearchBtnPanelLayout.setHorizontalGroup(
            cusSearchBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cusSearchBtnPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(searchCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        cusSearchBtnPanelLayout.setVerticalGroup(
            cusSearchBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cusSearchBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchCustomerBtn)
                .addGap(20, 20, 20))
        );

        customerDetailsFormPanel1.add(cusSearchBtnPanel);

        addCusBtnPanel1.setPreferredSize(new java.awt.Dimension(325, 250));

        cusIDLabel.setText("Customer ID:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cusIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(cusIDSearchResult, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cusIDLabel)
                    .addComponent(cusIDSearchResult, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        addCusBtnPanel1.add(jPanel4);

        jLabel5.setText("Name:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(cusNameSearchResult, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cusNameSearchResult, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        addCusBtnPanel1.add(jPanel5);

        jLabel12.setText("Address:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(cusAddressSearchResult, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cusAddressSearchResult, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        addCusBtnPanel1.add(jPanel6);

        jLabel15.setText("Total points:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(cusPointsSearchResult, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cusPointsSearchResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        addCusBtnPanel1.add(jPanel7);

        customerDetailsFormPanel1.add(addCusBtnPanel1);

        jPanel3.add(customerDetailsFormPanel1);

        clearInfoBtn.setText("Clear Data");

        javax.swing.GroupLayout clearDetailsPanelLayout = new javax.swing.GroupLayout(clearDetailsPanel);
        clearDetailsPanel.setLayout(clearDetailsPanelLayout);
        clearDetailsPanelLayout.setHorizontalGroup(
            clearDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clearDetailsPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(clearInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        clearDetailsPanelLayout.setVerticalGroup(
            clearDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clearDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clearInfoBtn)
                .addGap(20, 20, 20))
        );

        jPanel3.add(clearDetailsPanel);

        searchCustomerPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 5, 460, 470));

        panelLayer.add(searchCustomerPanel, "card2");

        addCashierPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addCashierTitlePanel.setPreferredSize(new java.awt.Dimension(440, 50));

        addCashierTitle.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        addCashierTitle.setText("Add New Cashier");

        javax.swing.GroupLayout addCashierTitlePanelLayout = new javax.swing.GroupLayout(addCashierTitlePanel);
        addCashierTitlePanel.setLayout(addCashierTitlePanelLayout);
        addCashierTitlePanelLayout.setHorizontalGroup(
            addCashierTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCashierTitlePanelLayout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(addCashierTitle)
                .addGap(156, 156, 156))
        );
        addCashierTitlePanelLayout.setVerticalGroup(
            addCashierTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCashierTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addCashierTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(addCashierTitlePanel);

        cashierDetailsFormPanel.setPreferredSize(new java.awt.Dimension(440, 300));

        cashNameLabel.setText("Cashier Name");

        javax.swing.GroupLayout cashNamePanelLayout = new javax.swing.GroupLayout(cashNamePanel);
        cashNamePanel.setLayout(cashNamePanelLayout);
        cashNamePanelLayout.setHorizontalGroup(
            cashNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cashNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cashNameLabel)
                    .addComponent(cashName, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        cashNamePanelLayout.setVerticalGroup(
            cashNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cashNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cashName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        addressLabel.setText("Username");

        javax.swing.GroupLayout addressPanelLayout = new javax.swing.GroupLayout(addressPanel);
        addressPanel.setLayout(addressPanelLayout);
        addressPanelLayout.setHorizontalGroup(
            addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressLabel)
                    .addComponent(cashAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        addressPanelLayout.setVerticalGroup(
            addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(addressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cashAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        usernameLabel.setText("Address");

        javax.swing.GroupLayout usernamePanelLayout = new javax.swing.GroupLayout(usernamePanel);
        usernamePanel.setLayout(usernamePanelLayout);
        usernamePanelLayout.setHorizontalGroup(
            usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameLabel)
                    .addComponent(cashUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        usernamePanelLayout.setVerticalGroup(
            usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernamePanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cashUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        passwordLabel.setText("Password");

        javax.swing.GroupLayout passwordPanelLayout = new javax.swing.GroupLayout(passwordPanel);
        passwordPanel.setLayout(passwordPanelLayout);
        passwordPanelLayout.setHorizontalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordLabel)
                    .addComponent(cashPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        passwordPanelLayout.setVerticalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cashPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        cashMobileLabel.setText("Cashier Mobile No.");

        cashMobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cashMobileKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout cashNamePanel1Layout = new javax.swing.GroupLayout(cashNamePanel1);
        cashNamePanel1.setLayout(cashNamePanel1Layout);
        cashNamePanel1Layout.setHorizontalGroup(
            cashNamePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashNamePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cashNamePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cashMobileLabel)
                    .addComponent(cashMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        cashNamePanel1Layout.setVerticalGroup(
            cashNamePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashNamePanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(cashMobileLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cashMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout cashierDetailsFormPanelLayout = new javax.swing.GroupLayout(cashierDetailsFormPanel);
        cashierDetailsFormPanel.setLayout(cashierDetailsFormPanelLayout);
        cashierDetailsFormPanelLayout.setHorizontalGroup(
            cashierDetailsFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cashierDetailsFormPanelLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(cashierDetailsFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cashNamePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        cashierDetailsFormPanelLayout.setVerticalGroup(
            cashierDetailsFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashierDetailsFormPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(cashNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cashNamePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(addressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel2.add(cashierDetailsFormPanel);

        addCashBtnPanel.setPreferredSize(new java.awt.Dimension(440, 50));

        addCashierBtn.setText("Add Cashier");

        javax.swing.GroupLayout addCashBtnPanelLayout = new javax.swing.GroupLayout(addCashBtnPanel);
        addCashBtnPanel.setLayout(addCashBtnPanelLayout);
        addCashBtnPanelLayout.setHorizontalGroup(
            addCashBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCashBtnPanelLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(addCashierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        addCashBtnPanelLayout.setVerticalGroup(
            addCashBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCashBtnPanelLayout.createSequentialGroup()
                .addComponent(addCashierBtn)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        jPanel2.add(addCashBtnPanel);

        addCashierPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 5, 460, 470));

        panelLayer.add(addCashierPanel, "card5");

        viewCashiersTitlePanel.setAlignmentX(5.0F);
        viewCashiersTitlePanel.setAlignmentY(5.0F);
        viewCashiersTitlePanel.setPreferredSize(new java.awt.Dimension(900, 50));

        viewCashiersTitle.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        viewCashiersTitle.setText("Cashier Details");
        viewCashiersTitle.setAlignmentX(1.0F);

        javax.swing.GroupLayout viewCashiersTitlePanelLayout = new javax.swing.GroupLayout(viewCashiersTitlePanel);
        viewCashiersTitlePanel.setLayout(viewCashiersTitlePanelLayout);
        viewCashiersTitlePanelLayout.setHorizontalGroup(
            viewCashiersTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewCashiersTitlePanelLayout.createSequentialGroup()
                .addContainerGap(437, Short.MAX_VALUE)
                .addComponent(viewCashiersTitle)
                .addGap(361, 361, 361))
        );
        viewCashiersTitlePanelLayout.setVerticalGroup(
            viewCashiersTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewCashiersTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewCashiersTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        viewCashiersPanel.add(viewCashiersTitlePanel);

        cashiersTablePanel.setPreferredSize(new java.awt.Dimension(900, 410));

        cashiersInfoTablePanel.setPreferredSize(new java.awt.Dimension(900, 403));

        cashiersInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cashier_ID", "Name", "Mobile No.", "Address", "Date Started", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cashiersInfoTable.setIntercellSpacing(new java.awt.Dimension(2, 2));
        cashiersInfoTable.setRowHeight(20);
        cashiersInfoTable.setShowGrid(true);
        cashiersInfoTablePanel.setViewportView(cashiersInfoTable);
        if (cashiersInfoTable.getColumnModel().getColumnCount() > 0) {
            cashiersInfoTable.getColumnModel().getColumn(0).setMinWidth(100);
            cashiersInfoTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            cashiersInfoTable.getColumnModel().getColumn(0).setMaxWidth(100);
            cashiersInfoTable.getColumnModel().getColumn(2).setMinWidth(120);
            cashiersInfoTable.getColumnModel().getColumn(2).setPreferredWidth(120);
            cashiersInfoTable.getColumnModel().getColumn(2).setMaxWidth(120);
            cashiersInfoTable.getColumnModel().getColumn(3).setHeaderValue("Address");
            cashiersInfoTable.getColumnModel().getColumn(4).setMinWidth(100);
            cashiersInfoTable.getColumnModel().getColumn(4).setPreferredWidth(100);
            cashiersInfoTable.getColumnModel().getColumn(4).setMaxWidth(100);
            cashiersInfoTable.getColumnModel().getColumn(4).setHeaderValue("Date Started");
            cashiersInfoTable.getColumnModel().getColumn(5).setMinWidth(150);
            cashiersInfoTable.getColumnModel().getColumn(5).setPreferredWidth(150);
            cashiersInfoTable.getColumnModel().getColumn(5).setMaxWidth(150);
        }

        cashiersTablePanel.add(cashiersInfoTablePanel);

        viewCashiersPanel.add(cashiersTablePanel);

        panelLayer.add(viewCashiersPanel, "card6");

        addProductPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addProductTitlePanel.setPreferredSize(new java.awt.Dimension(440, 50));

        addProductTitle.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        addProductTitle.setText("Add New Product");

        javax.swing.GroupLayout addProductTitlePanelLayout = new javax.swing.GroupLayout(addProductTitlePanel);
        addProductTitlePanel.setLayout(addProductTitlePanelLayout);
        addProductTitlePanelLayout.setHorizontalGroup(
            addProductTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addProductTitlePanelLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(addProductTitle)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        addProductTitlePanelLayout.setVerticalGroup(
            addProductTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addProductTitlePanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(addProductTitle)
                .addContainerGap())
        );

        jPanel8.add(addProductTitlePanel);

        productDetailsFormPanel.setPreferredSize(new java.awt.Dimension(440, 250));

        productNameLabel.setText("Product Name");

        productName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout productNamePanelLayout = new javax.swing.GroupLayout(productNamePanel);
        productNamePanel.setLayout(productNamePanelLayout);
        productNamePanelLayout.setHorizontalGroup(
            productNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productNameLabel)
                    .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        productNamePanelLayout.setVerticalGroup(
            productNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        productPriceLabel.setText("Product Price (Rs.)");

        productPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                productPriceFocusLost(evt);
            }
        });
        productPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productPriceKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout productPricePanelLayout = new javax.swing.GroupLayout(productPricePanel);
        productPricePanel.setLayout(productPricePanelLayout);
        productPricePanelLayout.setHorizontalGroup(
            productPricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPricePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productPricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productPriceLabel)
                    .addComponent(productPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        productPricePanelLayout.setVerticalGroup(
            productPricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPricePanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(productPriceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout productDetailsFormPanelLayout = new javax.swing.GroupLayout(productDetailsFormPanel);
        productDetailsFormPanel.setLayout(productDetailsFormPanelLayout);
        productDetailsFormPanelLayout.setHorizontalGroup(
            productDetailsFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productDetailsFormPanelLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(productDetailsFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productPricePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        productDetailsFormPanelLayout.setVerticalGroup(
            productDetailsFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productDetailsFormPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(productNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(productPricePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jPanel8.add(productDetailsFormPanel);

        addProductBtnPanel.setPreferredSize(new java.awt.Dimension(440, 50));

        addProductBtn.setText("Add Product");

        javax.swing.GroupLayout addProductBtnPanelLayout = new javax.swing.GroupLayout(addProductBtnPanel);
        addProductBtnPanel.setLayout(addProductBtnPanelLayout);
        addProductBtnPanelLayout.setHorizontalGroup(
            addProductBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addProductBtnPanelLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(addProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        addProductBtnPanelLayout.setVerticalGroup(
            addProductBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addProductBtnPanelLayout.createSequentialGroup()
                .addComponent(addProductBtn)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        jPanel8.add(addProductBtnPanel);

        addProductPanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 5, 460, 470));

        panelLayer.add(addProductPanel, "card7");

        viewProductsTitlePanel.setAlignmentX(5.0F);
        viewProductsTitlePanel.setAlignmentY(5.0F);
        viewProductsTitlePanel.setPreferredSize(new java.awt.Dimension(900, 50));

        viewCashiersTitle1.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        viewCashiersTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewCashiersTitle1.setText("Products");
        viewCashiersTitle1.setAlignmentX(1.0F);

        javax.swing.GroupLayout viewProductsTitlePanelLayout = new javax.swing.GroupLayout(viewProductsTitlePanel);
        viewProductsTitlePanel.setLayout(viewProductsTitlePanelLayout);
        viewProductsTitlePanelLayout.setHorizontalGroup(
            viewProductsTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewProductsTitlePanelLayout.createSequentialGroup()
                .addContainerGap(436, Short.MAX_VALUE)
                .addComponent(viewCashiersTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(361, 361, 361))
        );
        viewProductsTitlePanelLayout.setVerticalGroup(
            viewProductsTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewProductsTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewCashiersTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        viewProductsPanel.add(viewProductsTitlePanel);

        cashiersTablePanel1.setPreferredSize(new java.awt.Dimension(900, 410));

        cashiersInfoTablePanel1.setPreferredSize(new java.awt.Dimension(600, 403));

        cashiersInfoTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product_ID", "Name", "Price", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cashiersInfoTable1.setIntercellSpacing(new java.awt.Dimension(2, 2));
        cashiersInfoTable1.setRowHeight(20);
        cashiersInfoTable1.setShowGrid(true);
        cashiersInfoTablePanel1.setViewportView(cashiersInfoTable1);
        if (cashiersInfoTable1.getColumnModel().getColumnCount() > 0) {
            cashiersInfoTable1.getColumnModel().getColumn(0).setMinWidth(100);
            cashiersInfoTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            cashiersInfoTable1.getColumnModel().getColumn(0).setMaxWidth(100);
            cashiersInfoTable1.getColumnModel().getColumn(2).setMinWidth(120);
            cashiersInfoTable1.getColumnModel().getColumn(2).setPreferredWidth(120);
            cashiersInfoTable1.getColumnModel().getColumn(2).setMaxWidth(120);
            cashiersInfoTable1.getColumnModel().getColumn(3).setMinWidth(150);
            cashiersInfoTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
            cashiersInfoTable1.getColumnModel().getColumn(3).setMaxWidth(150);
        }

        cashiersTablePanel1.add(cashiersInfoTablePanel1);

        viewProductsPanel.add(cashiersTablePanel1);

        panelLayer.add(viewProductsPanel, "card8");

        settingsPanel.setMaximumSize(new java.awt.Dimension(900, 500));
        settingsPanel.setMinimumSize(new java.awt.Dimension(900, 500));
        settingsPanel.setPreferredSize(new java.awt.Dimension(900, 500));
        settingsPanel.setLayout(new java.awt.BorderLayout());

        left.setPreferredSize(new java.awt.Dimension(350, 500));

        adminMobile.setText("+94 76 123 7895");

        adminName.setText("John Doe");

        adminAddress.setText("21, Jump Street.");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminName, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adminAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adminMobile)
                .addContainerGap())
        );

        javax.swing.GroupLayout leftLayout = new javax.swing.GroupLayout(left);
        left.setLayout(leftLayout);
        leftLayout.setHorizontalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        leftLayout.setVerticalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        settingsPanel.add(left, java.awt.BorderLayout.WEST);

        right.setPreferredSize(new java.awt.Dimension(550, 500));

        rightTopPanel.setPreferredSize(new java.awt.Dimension(550, 200));

        myNamePanel.setPreferredSize(new java.awt.Dimension(450, 52));

        myNameLabel.setText("Name");

        javax.swing.GroupLayout myNamePanelLayout = new javax.swing.GroupLayout(myNamePanel);
        myNamePanel.setLayout(myNamePanelLayout);
        myNamePanelLayout.setHorizontalGroup(
            myNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(myNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myNamePanelLayout.createSequentialGroup()
                        .addComponent(myNameLabel)
                        .addGap(265, 411, Short.MAX_VALUE))
                    .addGroup(myNamePanelLayout.createSequentialGroup()
                        .addComponent(myName)
                        .addContainerGap())))
        );
        myNamePanelLayout.setVerticalGroup(
            myNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        rightTopPanel.add(myNamePanel);

        myAddressPanel.setPreferredSize(new java.awt.Dimension(450, 40));

        myAddressLabel.setText("Address");

        myAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myAddressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout myAddressPanelLayout = new javax.swing.GroupLayout(myAddressPanel);
        myAddressPanel.setLayout(myAddressPanelLayout);
        myAddressPanelLayout.setHorizontalGroup(
            myAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myAddressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(myAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myAddressPanelLayout.createSequentialGroup()
                        .addComponent(myAddressLabel)
                        .addGap(299, 396, Short.MAX_VALUE))
                    .addGroup(myAddressPanelLayout.createSequentialGroup()
                        .addComponent(myAddress)
                        .addContainerGap())))
        );
        myAddressPanelLayout.setVerticalGroup(
            myAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myAddressPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(myAddressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        rightTopPanel.add(myAddressPanel);

        myMobilePanel.setPreferredSize(new java.awt.Dimension(450, 56));

        myMobileLabel.setText("Mobile No.");

        javax.swing.GroupLayout myMobilePanelLayout = new javax.swing.GroupLayout(myMobilePanel);
        myMobilePanel.setLayout(myMobilePanelLayout);
        myMobilePanelLayout.setHorizontalGroup(
            myMobilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myMobilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(myMobilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myMobilePanelLayout.createSequentialGroup()
                        .addComponent(myMobileLabel)
                        .addGap(292, 389, Short.MAX_VALUE))
                    .addGroup(myMobilePanelLayout.createSequentialGroup()
                        .addComponent(myMobile)
                        .addContainerGap())))
        );
        myMobilePanelLayout.setVerticalGroup(
            myMobilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myMobilePanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(myMobileLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        rightTopPanel.add(myMobilePanel);

        myInfoActionPanel.setPreferredSize(new java.awt.Dimension(500, 40));

        saveChangesBtn.setText("Save Changes");
        saveChangesBtn.setPreferredSize(new java.awt.Dimension(75, 25));

        cancelChangesBtn.setText("Cancel");
        cancelChangesBtn.setMaximumSize(new java.awt.Dimension(75, 25));
        cancelChangesBtn.setMinimumSize(new java.awt.Dimension(75, 25));
        cancelChangesBtn.setPreferredSize(new java.awt.Dimension(75, 25));

        javax.swing.GroupLayout myInfoActionPanelLayout = new javax.swing.GroupLayout(myInfoActionPanel);
        myInfoActionPanel.setLayout(myInfoActionPanelLayout);
        myInfoActionPanelLayout.setHorizontalGroup(
            myInfoActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myInfoActionPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(saveChangesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(cancelChangesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        myInfoActionPanelLayout.setVerticalGroup(
            myInfoActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myInfoActionPanelLayout.createSequentialGroup()
                .addGroup(myInfoActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveChangesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelChangesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        rightTopPanel.add(myInfoActionPanel);

        right.add(rightTopPanel);

        rightBottomPanel.setPreferredSize(new java.awt.Dimension(550, 250));

        currPasswordLabel.setText("Current Password");

        javax.swing.GroupLayout currentPasswordPanelLayout = new javax.swing.GroupLayout(currentPasswordPanel);
        currentPasswordPanel.setLayout(currentPasswordPanelLayout);
        currentPasswordPanelLayout.setHorizontalGroup(
            currentPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentPasswordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(currentPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(currentPasswordPanelLayout.createSequentialGroup()
                        .addComponent(currPasswordLabel)
                        .addGap(265, 349, Short.MAX_VALUE))
                    .addGroup(currentPasswordPanelLayout.createSequentialGroup()
                        .addComponent(currPassword)
                        .addContainerGap())))
        );
        currentPasswordPanelLayout.setVerticalGroup(
            currentPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentPasswordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(currPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rightBottomPanel.add(currentPasswordPanel);

        newPasswordPanel.setPreferredSize(new java.awt.Dimension(450, 40));

        newPasswordLabel.setText("New Password");

        javax.swing.GroupLayout newPasswordPanelLayout = new javax.swing.GroupLayout(newPasswordPanel);
        newPasswordPanel.setLayout(newPasswordPanelLayout);
        newPasswordPanelLayout.setHorizontalGroup(
            newPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newPasswordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newPasswordPanelLayout.createSequentialGroup()
                        .addComponent(newPasswordLabel)
                        .addGap(299, 362, Short.MAX_VALUE))
                    .addGroup(newPasswordPanelLayout.createSequentialGroup()
                        .addComponent(newPassword)
                        .addContainerGap())))
        );
        newPasswordPanelLayout.setVerticalGroup(
            newPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newPasswordPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(newPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        rightBottomPanel.add(newPasswordPanel);

        confPasswordPanel.setPreferredSize(new java.awt.Dimension(450, 56));

        confPasswordLabel.setText("Confirm Password");

        javax.swing.GroupLayout confPasswordPanelLayout = new javax.swing.GroupLayout(confPasswordPanel);
        confPasswordPanel.setLayout(confPasswordPanelLayout);
        confPasswordPanelLayout.setHorizontalGroup(
            confPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confPasswordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(confPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(confPasswordPanelLayout.createSequentialGroup()
                        .addComponent(confPasswordLabel)
                        .addGap(292, 348, Short.MAX_VALUE))
                    .addGroup(confPasswordPanelLayout.createSequentialGroup()
                        .addComponent(confPassword)
                        .addContainerGap())))
        );
        confPasswordPanelLayout.setVerticalGroup(
            confPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confPasswordPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(confPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        rightBottomPanel.add(confPasswordPanel);

        myPasswordActionPanel.setPreferredSize(new java.awt.Dimension(500, 56));

        saveNewPasswordBtn.setText("Save Changes");
        saveNewPasswordBtn.setPreferredSize(new java.awt.Dimension(75, 25));

        cancelPasswordChangeBtn.setText("Cancel");
        cancelPasswordChangeBtn.setMaximumSize(new java.awt.Dimension(75, 25));
        cancelPasswordChangeBtn.setMinimumSize(new java.awt.Dimension(75, 25));
        cancelPasswordChangeBtn.setPreferredSize(new java.awt.Dimension(75, 25));

        javax.swing.GroupLayout myPasswordActionPanelLayout = new javax.swing.GroupLayout(myPasswordActionPanel);
        myPasswordActionPanel.setLayout(myPasswordActionPanelLayout);
        myPasswordActionPanelLayout.setHorizontalGroup(
            myPasswordActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPasswordActionPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(saveNewPasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(cancelPasswordChangeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        myPasswordActionPanelLayout.setVerticalGroup(
            myPasswordActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPasswordActionPanelLayout.createSequentialGroup()
                .addGroup(myPasswordActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveNewPasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelPasswordChangeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        rightBottomPanel.add(myPasswordActionPanel);

        right.add(rightBottomPanel);

        settingsPanel.add(right, java.awt.BorderLayout.CENTER);

        panelLayer.add(settingsPanel, "card9");

        viewCustomersTitlePanel.setAlignmentX(5.0F);
        viewCustomersTitlePanel.setAlignmentY(5.0F);
        viewCustomersTitlePanel.setPreferredSize(new java.awt.Dimension(900, 50));

        viewCustomersTitle.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        viewCustomersTitle.setText("Customer Details");
        viewCustomersTitle.setAlignmentX(1.0F);

        javax.swing.GroupLayout viewCustomersTitlePanelLayout = new javax.swing.GroupLayout(viewCustomersTitlePanel);
        viewCustomersTitlePanel.setLayout(viewCustomersTitlePanelLayout);
        viewCustomersTitlePanelLayout.setHorizontalGroup(
            viewCustomersTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewCustomersTitlePanelLayout.createSequentialGroup()
                .addContainerGap(423, Short.MAX_VALUE)
                .addComponent(viewCustomersTitle)
                .addGap(361, 361, 361))
        );
        viewCustomersTitlePanelLayout.setVerticalGroup(
            viewCustomersTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewCustomersTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewCustomersTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        viewCustomersPanel.add(viewCustomersTitlePanel);

        customersTablePanel.setPreferredSize(new java.awt.Dimension(900, 410));

        customersInfoTablePanel.setPreferredSize(new java.awt.Dimension(900, 403));

        customersInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Customer_ID", "Name", "Mobile No.", "Address", "Points"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customersInfoTable.setIntercellSpacing(new java.awt.Dimension(2, 2));
        customersInfoTable.setRowHeight(20);
        customersInfoTable.setShowGrid(true);
        customersInfoTablePanel.setViewportView(customersInfoTable);

        customersTablePanel.add(customersInfoTablePanel);

        viewCustomersPanel.add(customersTablePanel);

        panelLayer.add(viewCustomersPanel, "card3");

        viewSalesPanel.setMaximumSize(new java.awt.Dimension(900, 500));
        viewSalesPanel.setMinimumSize(new java.awt.Dimension(900, 500));
        viewSalesPanel.setPreferredSize(new java.awt.Dimension(900, 500));
        viewSalesPanel.setLayout(new java.awt.BorderLayout());

        salesPanel.setPreferredSize(new java.awt.Dimension(900, 520));
        salesPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        orderDetailsTitlePanel.setAlignmentX(5.0F);
        orderDetailsTitlePanel.setAlignmentY(5.0F);
        orderDetailsTitlePanel.setPreferredSize(new java.awt.Dimension(900, 50));

        orderSecTitle.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        orderSecTitle.setText("Order Details");
        orderSecTitle.setAlignmentX(1.0F);

        javax.swing.GroupLayout orderDetailsTitlePanelLayout = new javax.swing.GroupLayout(orderDetailsTitlePanel);
        orderDetailsTitlePanel.setLayout(orderDetailsTitlePanelLayout);
        orderDetailsTitlePanelLayout.setHorizontalGroup(
            orderDetailsTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderDetailsTitlePanelLayout.createSequentialGroup()
                .addContainerGap(450, Short.MAX_VALUE)
                .addComponent(orderSecTitle)
                .addGap(361, 361, 361))
        );
        orderDetailsTitlePanelLayout.setVerticalGroup(
            orderDetailsTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderDetailsTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderSecTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        salesPanel.add(orderDetailsTitlePanel);

        salesTablePanel.setPreferredSize(new java.awt.Dimension(900, 410));

        orderDetailsTablePanel.setPreferredSize(new java.awt.Dimension(900, 403));

        orderDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Order_ID", "Customer_Mobile", "Date", "Items", "Discount", "Points", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderDetailsTable.setIntercellSpacing(new java.awt.Dimension(2, 2));
        orderDetailsTable.setRowHeight(20);
        orderDetailsTable.setShowGrid(true);
        orderDetailsTablePanel.setViewportView(orderDetailsTable);

        salesTablePanel.add(orderDetailsTablePanel);

        salesPanel.add(salesTablePanel);

        viewSalesPanel.add(salesPanel, java.awt.BorderLayout.WEST);

        panelLayer.add(viewSalesPanel, "card4");

        getContentPane().add(panelLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 480));

        jMenu1.setText("Sales");

        jMenuItem1.setText("View Sales");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Customers");

        jMenuItem6.setText("View Customers");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem8.setText("Search Customer");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Cashier");

        jMenuItem2.setText("Add Cashier");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("View Cashiers");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Products");

        jMenuItem7.setText("Add Product");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuItem9.setText("View Products");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Profile");

        jMenuItem4.setText("Settings");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Logout");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        switchPanels(viewSalesPanel);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        switchPanels(viewCustomersPanel);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        switchPanels(searchCustomerPanel);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        switchPanels(settingsPanel);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        switchPanels(addCashierPanel);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        switchPanels(addProductPanel);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        switchPanels(viewCashiersPanel);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        switchPanels(viewProductsPanel);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void productNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameActionPerformed

    private void productPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productPriceKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_productPriceKeyTyped

    private void productPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productPriceFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_productPriceFocusLost

    private void cusMobileInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cusMobileInputKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_cusMobileInputKeyTyped

    private void cashMobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cashMobileKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_cashMobileKeyTyped

    private void myAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myAddressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
//        new JTextFieldValidation();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }
    
    public void switchPanels(JPanel panel){
        panelLayer.removeAll();
        panelLayer.add(panel);
        panelLayer.repaint();
        panelLayer.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addCashBtnPanel;
    private javax.swing.JButton addCashierBtn;
    private javax.swing.JPanel addCashierPanel;
    private javax.swing.JLabel addCashierTitle;
    private javax.swing.JPanel addCashierTitlePanel;
    private javax.swing.JPanel addCusBtnPanel1;
    private javax.swing.JLabel addCustomerTitle1;
    private javax.swing.JPanel addCustomerTitlePanel1;
    private javax.swing.JButton addProductBtn;
    private javax.swing.JPanel addProductBtnPanel;
    private javax.swing.JPanel addProductPanel;
    private javax.swing.JLabel addProductTitle;
    private javax.swing.JPanel addProductTitlePanel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JPanel addressPanel;
    private javax.swing.JLabel adminAddress;
    private javax.swing.JLabel adminMobile;
    private javax.swing.JLabel adminName;
    private javax.swing.JButton cancelChangesBtn;
    private javax.swing.JButton cancelPasswordChangeBtn;
    private javax.swing.JTextField cashAddress;
    private javax.swing.JTextField cashMobile;
    private javax.swing.JLabel cashMobileLabel;
    private javax.swing.JTextField cashName;
    private javax.swing.JLabel cashNameLabel;
    private javax.swing.JPanel cashNamePanel;
    private javax.swing.JPanel cashNamePanel1;
    private javax.swing.JTextField cashPassword;
    private javax.swing.JTextField cashUsername;
    private javax.swing.JPanel cashierDetailsFormPanel;
    private javax.swing.JTable cashiersInfoTable;
    private javax.swing.JTable cashiersInfoTable1;
    private javax.swing.JScrollPane cashiersInfoTablePanel;
    private javax.swing.JScrollPane cashiersInfoTablePanel1;
    private javax.swing.JPanel cashiersTablePanel;
    private javax.swing.JPanel cashiersTablePanel1;
    private javax.swing.JPanel clearDetailsPanel;
    private javax.swing.JButton clearInfoBtn;
    private javax.swing.JPasswordField confPassword;
    private javax.swing.JLabel confPasswordLabel;
    private javax.swing.JPanel confPasswordPanel;
    private javax.swing.JPasswordField currPassword;
    private javax.swing.JLabel currPasswordLabel;
    private javax.swing.JPanel currentPasswordPanel;
    private javax.swing.JLabel cusAddressSearchResult;
    private javax.swing.JLabel cusIDLabel;
    private javax.swing.JLabel cusIDSearchResult;
    private javax.swing.JTextField cusMobileInput;
    private javax.swing.JLabel cusNameSearchResult;
    private javax.swing.JLabel cusPointsSearchResult;
    private javax.swing.JPanel cusSearchBtnPanel;
    private javax.swing.JPanel cusSearchInputPanel;
    private javax.swing.JPanel customerDetailsFormPanel1;
    private javax.swing.JTable customersInfoTable;
    private javax.swing.JScrollPane customersInfoTablePanel;
    private javax.swing.JPanel customersTablePanel;
    private javax.swing.JLabel enterMobileNoLabel;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel left;
    private javax.swing.JTextField myAddress;
    private javax.swing.JLabel myAddressLabel;
    private javax.swing.JPanel myAddressPanel;
    private javax.swing.JPanel myInfoActionPanel;
    private javax.swing.JTextField myMobile;
    private javax.swing.JLabel myMobileLabel;
    private javax.swing.JPanel myMobilePanel;
    private javax.swing.JTextField myName;
    private javax.swing.JLabel myNameLabel;
    private javax.swing.JPanel myNamePanel;
    private javax.swing.JPanel myPasswordActionPanel;
    private javax.swing.JPasswordField newPassword;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JPanel newPasswordPanel;
    private javax.swing.JTable orderDetailsTable;
    private javax.swing.JScrollPane orderDetailsTablePanel;
    private javax.swing.JPanel orderDetailsTitlePanel;
    private javax.swing.JLabel orderSecTitle;
    private javax.swing.JLayeredPane panelLayer;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JPanel productDetailsFormPanel;
    private javax.swing.JTextField productName;
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JPanel productNamePanel;
    private javax.swing.JTextField productPrice;
    private javax.swing.JLabel productPriceLabel;
    private javax.swing.JPanel productPricePanel;
    private javax.swing.JPanel right;
    private javax.swing.JPanel rightBottomPanel;
    private javax.swing.JPanel rightTopPanel;
    private javax.swing.JPanel salesPanel;
    private javax.swing.JPanel salesTablePanel;
    private javax.swing.JButton saveChangesBtn;
    private javax.swing.JButton saveNewPasswordBtn;
    private javax.swing.JButton searchCustomerBtn;
    private javax.swing.JPanel searchCustomerPanel;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JPanel usernamePanel;
    private javax.swing.JPanel viewCashiersPanel;
    private javax.swing.JLabel viewCashiersTitle;
    private javax.swing.JLabel viewCashiersTitle1;
    private javax.swing.JPanel viewCashiersTitlePanel;
    private javax.swing.JPanel viewCustomersPanel;
    private javax.swing.JLabel viewCustomersTitle;
    private javax.swing.JPanel viewCustomersTitlePanel;
    private javax.swing.JPanel viewProductsPanel;
    private javax.swing.JPanel viewProductsTitlePanel;
    private javax.swing.JPanel viewSalesPanel;
    // End of variables declaration//GEN-END:variables
}
