/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.views;

import com.controllers.CashierController;
import com.controllers.CustomerController;
import com.controllers.SalesController;
import java.awt.event.HierarchyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Dictionary;
import java.util.Hashtable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;


/**
 *
 * @author BiGDoGKD
 */
public class CashierDashboard extends javax.swing.JFrame {

    /**
     * Creates new form CashierDashboard
     */
    Integer item = 0;
    Dictionary itemList = new Hashtable();
    List<Integer> priceList = new ArrayList();
    public CashierDashboard() throws SQLException {
        initComponents();
        setSize(900,520);
        setResizable(false);
        setVisible(true);
        
        super.setLocationRelativeTo(null);
        
        SalesController sc = new SalesController();
        String[][] products = sc.getProducts();
        System.out.println(products[0][1]);
        
        int i = 0;
        
        String[] a = new String[products.length];
        
        for(String[] product : products){
         a[i] = product[0];
         itemList.put(product[0], product[1]);
         i++;
        }
//        String[] a ={"asd","asd"};
        System.out.println(a);
        JComboBox c = new JComboBox(a);
        
        itemsTable.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(c));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cashierLayeredPane = new javax.swing.JLayeredPane();
        checkoutPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        panelTitle = new javax.swing.JLabel();
        itemsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemsTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        addItemBtn = new javax.swing.JButton();
        orderSummaryPanel = new javax.swing.JPanel();
        customerDetailsPanel = new javax.swing.JPanel();
        cutomerMobilePanel = new javax.swing.JPanel();
        cusMobilleLabel = new javax.swing.JLabel();
        customerMobileNo = new javax.swing.JTextField();
        verifyCustomerBtn = new javax.swing.JButton();
        totalPointsPanel = new javax.swing.JPanel();
        totalPointsLabel = new javax.swing.JLabel();
        totalPoints = new javax.swing.JLabel();
        addPointsPanel = new javax.swing.JPanel();
        pointsToAdd = new javax.swing.JTextField();
        addPointsBtn = new javax.swing.JButton();
        discountCheckPanel = new javax.swing.JPanel();
        addDiscountCheck = new javax.swing.JCheckBox();
        totalSummaryPanel = new javax.swing.JPanel();
        subtotalPanel = new javax.swing.JPanel();
        subtotal = new javax.swing.JLabel();
        subtotalLabel = new javax.swing.JLabel();
        discountPanel = new javax.swing.JPanel();
        discount = new javax.swing.JLabel();
        discountLabel = new javax.swing.JLabel();
        pointsPanel = new javax.swing.JPanel();
        points = new javax.swing.JLabel();
        pointsLabel = new javax.swing.JLabel();
        grossTotalPanel = new javax.swing.JPanel();
        grossTotal = new javax.swing.JLabel();
        grossTotalLabel = new javax.swing.JLabel();
        checkoutBtnPanel = new javax.swing.JPanel();
        checkoutBtn = new javax.swing.JButton();
        viewSalesPanel = new javax.swing.JPanel();
        salesPanel = new javax.swing.JPanel();
        orderDetailsTitlePanel = new javax.swing.JPanel();
        orderSecTitle = new javax.swing.JLabel();
        salesTablePanel = new javax.swing.JPanel();
        orderDetailsTablePanel = new javax.swing.JScrollPane();
        orderDetailsTable = new javax.swing.JTable();
        viewCustomersPanel = new javax.swing.JPanel();
        viewCustomersTitlePanel = new javax.swing.JPanel();
        viewCustomersTitle = new javax.swing.JLabel();
        customersTablePanel = new javax.swing.JPanel();
        customersInfoTablePanel = new javax.swing.JScrollPane();
        customersInfoTable = new javax.swing.JTable();
        addCustomerPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        addCustomerTitlePanel = new javax.swing.JPanel();
        addCustomerTitle = new javax.swing.JLabel();
        customerDetailsFormPanel = new javax.swing.JPanel();
        cusNamePanel = new javax.swing.JPanel();
        cusNameLabel = new javax.swing.JLabel();
        cusName = new javax.swing.JTextField();
        addressPanel = new javax.swing.JPanel();
        addressLabel = new javax.swing.JLabel();
        cusAddress = new javax.swing.JTextField();
        cusMobilePanel = new javax.swing.JPanel();
        cusMobileLabel = new javax.swing.JLabel();
        cusMobile = new javax.swing.JTextField();
        addCusBtnPanel = new javax.swing.JPanel();
        addCustomerBtn = new javax.swing.JButton();
        searchCustomerPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        addCustomerTitlePanel1 = new javax.swing.JPanel();
        addCustomerTitle1 = new javax.swing.JLabel();
        customerDetailsFormPanel1 = new javax.swing.JPanel();
        cusSearchInputPanel = new javax.swing.JPanel();
        enterMobileNoLabel = new javax.swing.JLabel();
        cusMobileInput = new javax.swing.JTextField();
        cusSearchBtnPanel = new javax.swing.JPanel();
        searchCustomerBtn = new javax.swing.JButton();
        addCusBtnPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cusIDSearchResult = new javax.swing.JLabel();
        cusIDLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        cusNameSearchResult = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        cusAddressSearchResult = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        cusPointsSearchResult = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        clearDetailsPanel = new javax.swing.JPanel();
        clearInfoBtn = new javax.swing.JButton();
        settingsPanel = new javax.swing.JPanel();
        left = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        cashMobile = new javax.swing.JLabel();
        cashName = new javax.swing.JLabel();
        cashAddress = new javax.swing.JLabel();
        right = new javax.swing.JPanel();
        rightTopPanel = new javax.swing.JPanel();
        myNamePanel = new javax.swing.JPanel();
        myNameLabel = new javax.swing.JLabel();
        myName = new javax.swing.JTextField();
        myAddressPanel = new javax.swing.JPanel();
        myAddressLabel = new javax.swing.JLabel();
        myAddress = new javax.swing.JTextField();
        myMobilePanel = new javax.swing.JPanel();
        myMobileLabel = new javax.swing.JLabel();
        myMobile = new javax.swing.JTextField();
        myInfoActionPanel = new javax.swing.JPanel();
        saveChangesBtn = new javax.swing.JButton();
        cancelChangesBtn = new javax.swing.JButton();
        rightBottomPanel = new javax.swing.JPanel();
        currentPasswordPanel = new javax.swing.JPanel();
        currPasswordLabel = new javax.swing.JLabel();
        currPassword = new javax.swing.JPasswordField();
        newPasswordPanel = new javax.swing.JPanel();
        newPasswordLabel = new javax.swing.JLabel();
        newPassword = new javax.swing.JPasswordField();
        confPasswordPanel = new javax.swing.JPanel();
        confPasswordLabel = new javax.swing.JLabel();
        confPassword = new javax.swing.JPasswordField();
        myPasswordActionPanel = new javax.swing.JPanel();
        saveNewPasswordBtn = new javax.swing.JButton();
        cancelPasswordChangeBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cashierLayeredPane.setPreferredSize(new java.awt.Dimension(900, 520));
        cashierLayeredPane.setLayout(new java.awt.CardLayout());

        checkoutPanel.setLayout(new java.awt.BorderLayout());

        titlePanel.setPreferredSize(new java.awt.Dimension(900, 60));

        panelTitle.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        panelTitle.setText("Checkout");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(426, Short.MAX_VALUE)
                .addComponent(panelTitle)
                .addGap(410, 410, 410))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        checkoutPanel.add(titlePanel, java.awt.BorderLayout.PAGE_START);

        itemsPanel.setPreferredSize(new java.awt.Dimension(550, 520));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(550, 350));

        itemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Item", "Quantity", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemsTable.setRowHeight(25);
        jScrollPane1.setViewportView(itemsTable);

        itemsPanel.add(jScrollPane1);

        jPanel1.setPreferredSize(new java.awt.Dimension(550, 100));

        addItemBtn.setText("Add Item");
        addItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 377, Short.MAX_VALUE)
                .addComponent(addItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(addItemBtn)
                .addGap(0, 75, Short.MAX_VALUE))
        );

        itemsPanel.add(jPanel1);

        checkoutPanel.add(itemsPanel, java.awt.BorderLayout.WEST);

        orderSummaryPanel.setPreferredSize(new java.awt.Dimension(350, 520));

        customerDetailsPanel.setPreferredSize(new java.awt.Dimension(350, 150));

        cutomerMobilePanel.setPreferredSize(new java.awt.Dimension(321, 65));

        cusMobilleLabel.setText("Customer Mobile No:");

        customerMobileNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                customerMobileNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                customerMobileNoKeyTyped(evt);
            }
        });

        verifyCustomerBtn.setText("Verify");
        verifyCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyCustomerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cutomerMobilePanelLayout = new javax.swing.GroupLayout(cutomerMobilePanel);
        cutomerMobilePanel.setLayout(cutomerMobilePanelLayout);
        cutomerMobilePanelLayout.setHorizontalGroup(
            cutomerMobilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cutomerMobilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cutomerMobilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cutomerMobilePanelLayout.createSequentialGroup()
                        .addComponent(cusMobilleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(customerMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cutomerMobilePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(verifyCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        cutomerMobilePanelLayout.setVerticalGroup(
            cutomerMobilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cutomerMobilePanelLayout.createSequentialGroup()
                .addGroup(cutomerMobilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cutomerMobilePanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(cusMobilleLabel))
                    .addComponent(customerMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(verifyCustomerBtn)
                .addContainerGap())
        );

        customerDetailsPanel.add(cutomerMobilePanel);

        totalPointsPanel.setPreferredSize(new java.awt.Dimension(321, 40));

        totalPointsLabel.setText("Total Points:");

        totalPoints.setPreferredSize(new java.awt.Dimension(0, 20));

        javax.swing.GroupLayout totalPointsPanelLayout = new javax.swing.GroupLayout(totalPointsPanel);
        totalPointsPanel.setLayout(totalPointsPanelLayout);
        totalPointsPanelLayout.setHorizontalGroup(
            totalPointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalPointsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalPointsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(totalPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        totalPointsPanelLayout.setVerticalGroup(
            totalPointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalPointsPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(totalPointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPointsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        customerDetailsPanel.add(totalPointsPanel);

        addPointsPanel.setPreferredSize(new java.awt.Dimension(321, 40));

        addPointsBtn.setText("Add Points");
        addPointsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPointsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPointsPanelLayout = new javax.swing.GroupLayout(addPointsPanel);
        addPointsPanel.setLayout(addPointsPanelLayout);
        addPointsPanelLayout.setHorizontalGroup(
            addPointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPointsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pointsToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(addPointsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        addPointsPanelLayout.setVerticalGroup(
            addPointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPointsPanelLayout.createSequentialGroup()
                .addComponent(addPointsBtn)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPointsPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pointsToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        customerDetailsPanel.add(addPointsPanel);

        orderSummaryPanel.add(customerDetailsPanel);

        discountCheckPanel.setPreferredSize(new java.awt.Dimension(350, 30));

        addDiscountCheck.setText("Add Discount");
        addDiscountCheck.setIconTextGap(10);
        addDiscountCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDiscountCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout discountCheckPanelLayout = new javax.swing.GroupLayout(discountCheckPanel);
        discountCheckPanel.setLayout(discountCheckPanelLayout);
        discountCheckPanelLayout.setHorizontalGroup(
            discountCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, discountCheckPanelLayout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(addDiscountCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        discountCheckPanelLayout.setVerticalGroup(
            discountCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(discountCheckPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(addDiscountCheck)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        orderSummaryPanel.add(discountCheckPanel);

        totalSummaryPanel.setPreferredSize(new java.awt.Dimension(350, 125));
        totalSummaryPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 2, 0));

        subtotalPanel.setPreferredSize(new java.awt.Dimension(321, 30));

        subtotalLabel.setText("Subtotal");

        javax.swing.GroupLayout subtotalPanelLayout = new javax.swing.GroupLayout(subtotalPanel);
        subtotalPanel.setLayout(subtotalPanelLayout);
        subtotalPanelLayout.setHorizontalGroup(
            subtotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subtotalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subtotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        subtotalPanelLayout.setVerticalGroup(
            subtotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subtotalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subtotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(subtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subtotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        totalSummaryPanel.add(subtotalPanel);

        discountPanel.setPreferredSize(new java.awt.Dimension(321, 30));

        discountLabel.setText("Discount");

        javax.swing.GroupLayout discountPanelLayout = new javax.swing.GroupLayout(discountPanel);
        discountPanel.setLayout(discountPanelLayout);
        discountPanelLayout.setHorizontalGroup(
            discountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(discountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(discountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        discountPanelLayout.setVerticalGroup(
            discountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(discountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(discountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(discountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(discount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3))
        );

        totalSummaryPanel.add(discountPanel);

        pointsPanel.setPreferredSize(new java.awt.Dimension(321, 30));

        pointsLabel.setText("Points");

        javax.swing.GroupLayout pointsPanelLayout = new javax.swing.GroupLayout(pointsPanel);
        pointsPanel.setLayout(pointsPanelLayout);
        pointsPanelLayout.setHorizontalGroup(
            pointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pointsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pointsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(points, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pointsPanelLayout.setVerticalGroup(
            pointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pointsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pointsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(points, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        totalSummaryPanel.add(pointsPanel);

        grossTotalPanel.setPreferredSize(new java.awt.Dimension(321, 30));

        grossTotalLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        grossTotalLabel.setText("Gross total");

        javax.swing.GroupLayout grossTotalPanelLayout = new javax.swing.GroupLayout(grossTotalPanel);
        grossTotalPanel.setLayout(grossTotalPanelLayout);
        grossTotalPanelLayout.setHorizontalGroup(
            grossTotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grossTotalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(grossTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(grossTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        grossTotalPanelLayout.setVerticalGroup(
            grossTotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grossTotalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(grossTotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(grossTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(grossTotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        totalSummaryPanel.add(grossTotalPanel);

        orderSummaryPanel.add(totalSummaryPanel);

        checkoutBtnPanel.setPreferredSize(new java.awt.Dimension(350, 50));

        checkoutBtn.setText("Checkout");

        javax.swing.GroupLayout checkoutBtnPanelLayout = new javax.swing.GroupLayout(checkoutBtnPanel);
        checkoutBtnPanel.setLayout(checkoutBtnPanelLayout);
        checkoutBtnPanelLayout.setHorizontalGroup(
            checkoutBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutBtnPanelLayout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addComponent(checkoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        checkoutBtnPanelLayout.setVerticalGroup(
            checkoutBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkoutBtn)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        orderSummaryPanel.add(checkoutBtnPanel);

        checkoutPanel.add(orderSummaryPanel, java.awt.BorderLayout.LINE_END);

        cashierLayeredPane.add(checkoutPanel, "card2");

        viewSalesPanel.setPreferredSize(new java.awt.Dimension(900, 500));
        viewSalesPanel.setLayout(new java.awt.BorderLayout(10, 10));

        salesPanel.setPreferredSize(new java.awt.Dimension(900, 520));
        salesPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        orderDetailsTitlePanel.setAlignmentX(5.0F);
        orderDetailsTitlePanel.setAlignmentY(5.0F);
        orderDetailsTitlePanel.setPreferredSize(new java.awt.Dimension(900, 50));

        orderSecTitle.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        orderSecTitle.setText("Order Details");
        orderSecTitle.setAlignmentX(1.0F);

        javax.swing.GroupLayout orderDetailsTitlePanelLayout = new javax.swing.GroupLayout(orderDetailsTitlePanel);
        orderDetailsTitlePanel.setLayout(orderDetailsTitlePanelLayout);
        orderDetailsTitlePanelLayout.setHorizontalGroup(
            orderDetailsTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderDetailsTitlePanelLayout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(orderSecTitle)
                .addContainerGap(415, Short.MAX_VALUE))
        );
        orderDetailsTitlePanelLayout.setVerticalGroup(
            orderDetailsTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderDetailsTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderSecTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        salesPanel.add(orderDetailsTitlePanel);

        salesTablePanel.setPreferredSize(new java.awt.Dimension(900, 410));

        orderDetailsTablePanel.setPreferredSize(new java.awt.Dimension(900, 403));

        orderDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Order_ID", "Customer_Mobile", "Date", "Discount", "Points", "Total", "Items"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderDetailsTable.setIntercellSpacing(new java.awt.Dimension(2, 2));
        orderDetailsTable.setMaximumSize(new java.awt.Dimension(900, 500));
        orderDetailsTable.setPreferredSize(new java.awt.Dimension(900, 500));
        orderDetailsTable.setRowHeight(20);
        orderDetailsTable.setShowGrid(true);
        orderDetailsTable.getTableHeader().setReorderingAllowed(false);
        orderDetailsTable.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                orderDetailsTableHierarchyChanged(evt);
            }
        });
        orderDetailsTablePanel.setViewportView(orderDetailsTable);
        if (orderDetailsTable.getColumnModel().getColumnCount() > 0) {
            orderDetailsTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            orderDetailsTable.getColumnModel().getColumn(0).setMaxWidth(100);
            orderDetailsTable.getColumnModel().getColumn(2).setPreferredWidth(120);
            orderDetailsTable.getColumnModel().getColumn(2).setMaxWidth(120);
            orderDetailsTable.getColumnModel().getColumn(3).setPreferredWidth(60);
            orderDetailsTable.getColumnModel().getColumn(4).setPreferredWidth(100);
            orderDetailsTable.getColumnModel().getColumn(4).setMaxWidth(100);
            orderDetailsTable.getColumnModel().getColumn(5).setPreferredWidth(60);
        }

        salesTablePanel.add(orderDetailsTablePanel);

        salesPanel.add(salesTablePanel);

        viewSalesPanel.add(salesPanel, java.awt.BorderLayout.WEST);

        cashierLayeredPane.add(viewSalesPanel, "card3");

        viewCustomersTitlePanel.setAlignmentX(5.0F);
        viewCustomersTitlePanel.setAlignmentY(5.0F);
        viewCustomersTitlePanel.setPreferredSize(new java.awt.Dimension(900, 50));

        viewCustomersTitle.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        viewCustomersTitle.setText("Customer Details");
        viewCustomersTitle.setAlignmentX(1.0F);

        javax.swing.GroupLayout viewCustomersTitlePanelLayout = new javax.swing.GroupLayout(viewCustomersTitlePanel);
        viewCustomersTitlePanel.setLayout(viewCustomersTitlePanelLayout);
        viewCustomersTitlePanelLayout.setHorizontalGroup(
            viewCustomersTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewCustomersTitlePanelLayout.createSequentialGroup()
                .addContainerGap(423, Short.MAX_VALUE)
                .addComponent(viewCustomersTitle)
                .addGap(361, 361, 361))
        );
        viewCustomersTitlePanelLayout.setVerticalGroup(
            viewCustomersTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewCustomersTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewCustomersTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        viewCustomersPanel.add(viewCustomersTitlePanel);

        customersTablePanel.setPreferredSize(new java.awt.Dimension(900, 410));

        customersInfoTablePanel.setPreferredSize(new java.awt.Dimension(900, 403));

        customersInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer_ID", "Name", "Mobile No.", "Address", "Points"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customersInfoTable.setIntercellSpacing(new java.awt.Dimension(2, 2));
        customersInfoTable.setRowHeight(20);
        customersInfoTable.setShowGrid(true);
        customersInfoTable.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                customersInfoTableHierarchyChanged(evt);
            }
        });
        customersInfoTablePanel.setViewportView(customersInfoTable);

        customersTablePanel.add(customersInfoTablePanel);

        viewCustomersPanel.add(customersTablePanel);

        cashierLayeredPane.add(viewCustomersPanel, "card4");

        addCustomerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addCustomerTitlePanel.setPreferredSize(new java.awt.Dimension(440, 50));

        addCustomerTitle.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        addCustomerTitle.setText("Add New Customer");

        javax.swing.GroupLayout addCustomerTitlePanelLayout = new javax.swing.GroupLayout(addCustomerTitlePanel);
        addCustomerTitlePanel.setLayout(addCustomerTitlePanelLayout);
        addCustomerTitlePanelLayout.setHorizontalGroup(
            addCustomerTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCustomerTitlePanelLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(addCustomerTitle)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        addCustomerTitlePanelLayout.setVerticalGroup(
            addCustomerTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCustomerTitlePanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(addCustomerTitle)
                .addContainerGap())
        );

        jPanel2.add(addCustomerTitlePanel);

        customerDetailsFormPanel.setPreferredSize(new java.awt.Dimension(440, 250));

        cusNameLabel.setText("Customer Name");

        javax.swing.GroupLayout cusNamePanelLayout = new javax.swing.GroupLayout(cusNamePanel);
        cusNamePanel.setLayout(cusNamePanelLayout);
        cusNamePanelLayout.setHorizontalGroup(
            cusNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cusNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cusNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cusNameLabel)
                    .addComponent(cusName, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        cusNamePanelLayout.setVerticalGroup(
            cusNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cusNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cusNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        addressLabel.setText("Address");

        javax.swing.GroupLayout addressPanelLayout = new javax.swing.GroupLayout(addressPanel);
        addressPanel.setLayout(addressPanelLayout);
        addressPanelLayout.setHorizontalGroup(
            addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressLabel)
                    .addComponent(cusAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        addressPanelLayout.setVerticalGroup(
            addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(addressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cusAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        cusMobileLabel.setText("Mobile No.");

        javax.swing.GroupLayout cusMobilePanelLayout = new javax.swing.GroupLayout(cusMobilePanel);
        cusMobilePanel.setLayout(cusMobilePanelLayout);
        cusMobilePanelLayout.setHorizontalGroup(
            cusMobilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cusMobilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cusMobilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cusMobileLabel)
                    .addComponent(cusMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        cusMobilePanelLayout.setVerticalGroup(
            cusMobilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cusMobilePanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(cusMobileLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cusMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout customerDetailsFormPanelLayout = new javax.swing.GroupLayout(customerDetailsFormPanel);
        customerDetailsFormPanel.setLayout(customerDetailsFormPanelLayout);
        customerDetailsFormPanelLayout.setHorizontalGroup(
            customerDetailsFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerDetailsFormPanelLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(customerDetailsFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cusMobilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cusNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        customerDetailsFormPanelLayout.setVerticalGroup(
            customerDetailsFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerDetailsFormPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(cusNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(cusMobilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel2.add(customerDetailsFormPanel);

        addCusBtnPanel.setPreferredSize(new java.awt.Dimension(440, 50));

        addCustomerBtn.setText("Add Customer");
        addCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addCusBtnPanelLayout = new javax.swing.GroupLayout(addCusBtnPanel);
        addCusBtnPanel.setLayout(addCusBtnPanelLayout);
        addCusBtnPanelLayout.setHorizontalGroup(
            addCusBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCusBtnPanelLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(addCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        addCusBtnPanelLayout.setVerticalGroup(
            addCusBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCusBtnPanelLayout.createSequentialGroup()
                .addComponent(addCustomerBtn)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        jPanel2.add(addCusBtnPanel);

        addCustomerPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 5, 460, 470));

        cashierLayeredPane.add(addCustomerPanel, "card5");

        searchCustomerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addCustomerTitlePanel1.setPreferredSize(new java.awt.Dimension(440, 50));

        addCustomerTitle1.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        addCustomerTitle1.setText("Search Customer");

        javax.swing.GroupLayout addCustomerTitlePanel1Layout = new javax.swing.GroupLayout(addCustomerTitlePanel1);
        addCustomerTitlePanel1.setLayout(addCustomerTitlePanel1Layout);
        addCustomerTitlePanel1Layout.setHorizontalGroup(
            addCustomerTitlePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCustomerTitlePanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(addCustomerTitle1)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        addCustomerTitlePanel1Layout.setVerticalGroup(
            addCustomerTitlePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCustomerTitlePanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(addCustomerTitle1)
                .addContainerGap())
        );

        jPanel3.add(addCustomerTitlePanel1);

        customerDetailsFormPanel1.setPreferredSize(new java.awt.Dimension(440, 280));

        enterMobileNoLabel.setText("Enter Customer Mobile No.");

        javax.swing.GroupLayout cusSearchInputPanelLayout = new javax.swing.GroupLayout(cusSearchInputPanel);
        cusSearchInputPanel.setLayout(cusSearchInputPanelLayout);
        cusSearchInputPanelLayout.setHorizontalGroup(
            cusSearchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cusSearchInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cusSearchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterMobileNoLabel)
                    .addComponent(cusMobileInput, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        cusSearchInputPanelLayout.setVerticalGroup(
            cusSearchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cusSearchInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterMobileNoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cusMobileInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        customerDetailsFormPanel1.add(cusSearchInputPanel);

        searchCustomerBtn.setText("Search Customer");
        searchCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustomerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cusSearchBtnPanelLayout = new javax.swing.GroupLayout(cusSearchBtnPanel);
        cusSearchBtnPanel.setLayout(cusSearchBtnPanelLayout);
        cusSearchBtnPanelLayout.setHorizontalGroup(
            cusSearchBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cusSearchBtnPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(searchCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        cusSearchBtnPanelLayout.setVerticalGroup(
            cusSearchBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cusSearchBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchCustomerBtn)
                .addGap(20, 20, 20))
        );

        customerDetailsFormPanel1.add(cusSearchBtnPanel);

        addCusBtnPanel1.setPreferredSize(new java.awt.Dimension(325, 250));

        cusIDLabel.setText("Customer ID:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cusIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(cusIDSearchResult, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cusIDLabel)
                    .addComponent(cusIDSearchResult, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        addCusBtnPanel1.add(jPanel4);

        jLabel4.setText("Name:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(cusNameSearchResult, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cusNameSearchResult, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        addCusBtnPanel1.add(jPanel5);

        jLabel6.setText("Address:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(cusAddressSearchResult, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cusAddressSearchResult, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        addCusBtnPanel1.add(jPanel6);

        jLabel9.setText("Total points:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(cusPointsSearchResult, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cusPointsSearchResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        addCusBtnPanel1.add(jPanel7);

        customerDetailsFormPanel1.add(addCusBtnPanel1);

        jPanel3.add(customerDetailsFormPanel1);

        clearInfoBtn.setText("Clear Data");

        javax.swing.GroupLayout clearDetailsPanelLayout = new javax.swing.GroupLayout(clearDetailsPanel);
        clearDetailsPanel.setLayout(clearDetailsPanelLayout);
        clearDetailsPanelLayout.setHorizontalGroup(
            clearDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clearDetailsPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(clearInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        clearDetailsPanelLayout.setVerticalGroup(
            clearDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clearDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clearInfoBtn)
                .addGap(20, 20, 20))
        );

        jPanel3.add(clearDetailsPanel);

        searchCustomerPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 5, 460, 470));

        cashierLayeredPane.add(searchCustomerPanel, "card6");

        settingsPanel.setLayout(new java.awt.BorderLayout());

        left.setPreferredSize(new java.awt.Dimension(350, 500));
        left.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                leftHierarchyChanged(evt);
            }
        });

        cashMobile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cashName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cashAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cashMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashName, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(cashName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cashAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cashMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout leftLayout = new javax.swing.GroupLayout(left);
        left.setLayout(leftLayout);
        leftLayout.setHorizontalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        leftLayout.setVerticalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        settingsPanel.add(left, java.awt.BorderLayout.WEST);

        right.setPreferredSize(new java.awt.Dimension(550, 500));

        rightTopPanel.setPreferredSize(new java.awt.Dimension(550, 200));

        myNamePanel.setPreferredSize(new java.awt.Dimension(450, 52));

        myNameLabel.setText("Name");

        javax.swing.GroupLayout myNamePanelLayout = new javax.swing.GroupLayout(myNamePanel);
        myNamePanel.setLayout(myNamePanelLayout);
        myNamePanelLayout.setHorizontalGroup(
            myNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(myNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myNamePanelLayout.createSequentialGroup()
                        .addComponent(myNameLabel)
                        .addGap(265, 411, Short.MAX_VALUE))
                    .addGroup(myNamePanelLayout.createSequentialGroup()
                        .addComponent(myName)
                        .addContainerGap())))
        );
        myNamePanelLayout.setVerticalGroup(
            myNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        rightTopPanel.add(myNamePanel);

        myAddressPanel.setPreferredSize(new java.awt.Dimension(450, 40));

        myAddressLabel.setText("Address");

        myAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myAddressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout myAddressPanelLayout = new javax.swing.GroupLayout(myAddressPanel);
        myAddressPanel.setLayout(myAddressPanelLayout);
        myAddressPanelLayout.setHorizontalGroup(
            myAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myAddressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(myAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myAddressPanelLayout.createSequentialGroup()
                        .addComponent(myAddressLabel)
                        .addGap(299, 396, Short.MAX_VALUE))
                    .addGroup(myAddressPanelLayout.createSequentialGroup()
                        .addComponent(myAddress)
                        .addContainerGap())))
        );
        myAddressPanelLayout.setVerticalGroup(
            myAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myAddressPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(myAddressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        rightTopPanel.add(myAddressPanel);

        myMobilePanel.setPreferredSize(new java.awt.Dimension(450, 56));

        myMobileLabel.setText("Mobile No.");

        javax.swing.GroupLayout myMobilePanelLayout = new javax.swing.GroupLayout(myMobilePanel);
        myMobilePanel.setLayout(myMobilePanelLayout);
        myMobilePanelLayout.setHorizontalGroup(
            myMobilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myMobilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(myMobilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myMobilePanelLayout.createSequentialGroup()
                        .addComponent(myMobileLabel)
                        .addGap(292, 389, Short.MAX_VALUE))
                    .addGroup(myMobilePanelLayout.createSequentialGroup()
                        .addComponent(myMobile)
                        .addContainerGap())))
        );
        myMobilePanelLayout.setVerticalGroup(
            myMobilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myMobilePanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(myMobileLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        rightTopPanel.add(myMobilePanel);

        myInfoActionPanel.setPreferredSize(new java.awt.Dimension(500, 40));

        saveChangesBtn.setText("Save Changes");
        saveChangesBtn.setPreferredSize(new java.awt.Dimension(75, 25));

        cancelChangesBtn.setText("Cancel");
        cancelChangesBtn.setMaximumSize(new java.awt.Dimension(75, 25));
        cancelChangesBtn.setMinimumSize(new java.awt.Dimension(75, 25));
        cancelChangesBtn.setPreferredSize(new java.awt.Dimension(75, 25));

        javax.swing.GroupLayout myInfoActionPanelLayout = new javax.swing.GroupLayout(myInfoActionPanel);
        myInfoActionPanel.setLayout(myInfoActionPanelLayout);
        myInfoActionPanelLayout.setHorizontalGroup(
            myInfoActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myInfoActionPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(saveChangesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(cancelChangesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        myInfoActionPanelLayout.setVerticalGroup(
            myInfoActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myInfoActionPanelLayout.createSequentialGroup()
                .addGroup(myInfoActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveChangesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelChangesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        rightTopPanel.add(myInfoActionPanel);

        right.add(rightTopPanel);

        rightBottomPanel.setPreferredSize(new java.awt.Dimension(550, 230));

        currPasswordLabel.setText("Current Password");

        javax.swing.GroupLayout currentPasswordPanelLayout = new javax.swing.GroupLayout(currentPasswordPanel);
        currentPasswordPanel.setLayout(currentPasswordPanelLayout);
        currentPasswordPanelLayout.setHorizontalGroup(
            currentPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentPasswordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(currentPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(currentPasswordPanelLayout.createSequentialGroup()
                        .addComponent(currPasswordLabel)
                        .addGap(265, 349, Short.MAX_VALUE))
                    .addGroup(currentPasswordPanelLayout.createSequentialGroup()
                        .addComponent(currPassword)
                        .addContainerGap())))
        );
        currentPasswordPanelLayout.setVerticalGroup(
            currentPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentPasswordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(currPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rightBottomPanel.add(currentPasswordPanel);

        newPasswordPanel.setPreferredSize(new java.awt.Dimension(450, 40));

        newPasswordLabel.setText("New Password");

        javax.swing.GroupLayout newPasswordPanelLayout = new javax.swing.GroupLayout(newPasswordPanel);
        newPasswordPanel.setLayout(newPasswordPanelLayout);
        newPasswordPanelLayout.setHorizontalGroup(
            newPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newPasswordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newPasswordPanelLayout.createSequentialGroup()
                        .addComponent(newPasswordLabel)
                        .addGap(299, 362, Short.MAX_VALUE))
                    .addGroup(newPasswordPanelLayout.createSequentialGroup()
                        .addComponent(newPassword)
                        .addContainerGap())))
        );
        newPasswordPanelLayout.setVerticalGroup(
            newPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newPasswordPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(newPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rightBottomPanel.add(newPasswordPanel);

        confPasswordPanel.setPreferredSize(new java.awt.Dimension(450, 56));

        confPasswordLabel.setText("Confirm Password");

        javax.swing.GroupLayout confPasswordPanelLayout = new javax.swing.GroupLayout(confPasswordPanel);
        confPasswordPanel.setLayout(confPasswordPanelLayout);
        confPasswordPanelLayout.setHorizontalGroup(
            confPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confPasswordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(confPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(confPasswordPanelLayout.createSequentialGroup()
                        .addComponent(confPasswordLabel)
                        .addGap(292, 348, Short.MAX_VALUE))
                    .addGroup(confPasswordPanelLayout.createSequentialGroup()
                        .addComponent(confPassword)
                        .addContainerGap())))
        );
        confPasswordPanelLayout.setVerticalGroup(
            confPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confPasswordPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(confPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        rightBottomPanel.add(confPasswordPanel);

        myPasswordActionPanel.setPreferredSize(new java.awt.Dimension(500, 56));

        saveNewPasswordBtn.setText("Save Changes");
        saveNewPasswordBtn.setPreferredSize(new java.awt.Dimension(75, 25));

        cancelPasswordChangeBtn.setText("Cancel");
        cancelPasswordChangeBtn.setMaximumSize(new java.awt.Dimension(75, 25));
        cancelPasswordChangeBtn.setMinimumSize(new java.awt.Dimension(75, 25));
        cancelPasswordChangeBtn.setPreferredSize(new java.awt.Dimension(75, 25));

        javax.swing.GroupLayout myPasswordActionPanelLayout = new javax.swing.GroupLayout(myPasswordActionPanel);
        myPasswordActionPanel.setLayout(myPasswordActionPanelLayout);
        myPasswordActionPanelLayout.setHorizontalGroup(
            myPasswordActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPasswordActionPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(saveNewPasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(cancelPasswordChangeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        myPasswordActionPanelLayout.setVerticalGroup(
            myPasswordActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPasswordActionPanelLayout.createSequentialGroup()
                .addGroup(myPasswordActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveNewPasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelPasswordChangeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        rightBottomPanel.add(myPasswordActionPanel);

        right.add(rightBottomPanel);

        settingsPanel.add(right, java.awt.BorderLayout.CENTER);

        cashierLayeredPane.add(settingsPanel, "card7");

        getContentPane().add(cashierLayeredPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        jMenu1.setText("Sales");

        jMenuItem1.setText("View Sales");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Chekout");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Customers");

        jMenuItem6.setText("View Customers");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Add Customer");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Search Customer");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Profile");

        jMenuItem4.setText("Settings");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Logout");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        switchPanels(viewSalesPanel);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        switchPanels(viewCustomersPanel);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        switchPanels(checkoutPanel);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        switchPanels(addCustomerPanel);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        switchPanels(searchCustomerPanel);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        switchPanels(settingsPanel);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void addDiscountCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDiscountCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDiscountCheckActionPerformed

    private void addItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemBtnActionPerformed
        // TODO add your handling code here:
        //itemsTable.setCellSelectionEnabled(true);
        //itemsTable.changeSelection(item, 3, false, false);
        //itemsTable.requestFocus();
        DefaultTableModel model = (DefaultTableModel)itemsTable.getModel();
        String itemName = itemsTable.getModel().getValueAt(item,0).toString();
        Integer itemQuantity = Integer.parseInt(itemsTable.getModel().getValueAt(item, 1).toString());
        Integer itemPrice = Integer.parseInt(itemList.get(itemName).toString());
//        System.out.println(itemName + "" + itemQuantity + "" + itemPrice*itemQuantity);
        priceList.add(itemPrice*itemQuantity);
        itemsTable.getModel().setValueAt(itemPrice*itemQuantity, item, 2);
//        System.out.println(priceList.stream().mapToInt(Integer::intValue).sum());
        item++;
        model.addRow(new Object[]{});
    }//GEN-LAST:event_addItemBtnActionPerformed

    private void myAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myAddressActionPerformed

    private void addCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerBtnActionPerformed
        // TODO add your handling code here:
        CustomerController cc = new CustomerController();
        cc.setName(cusName.getText());
        cc.setAddress(cusAddress.getText());
        cc.setMobile(cusMobile.getText());
        try {
            if (cc.createCustomer()) {
                JOptionPane.showMessageDialog(null, "Customer added successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "Action failed");
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addCustomerBtnActionPerformed

    private void customersInfoTableHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_customersInfoTableHierarchyChanged
        // TODO add your handling code here:
                //Customer Info
        if ((HierarchyEvent.SHOWING_CHANGED & evt.getChangeFlags()) != 0 && customersInfoTable.isShowing()) {
            try {
                List<CustomerController> customers = CustomerController.viewCustomers();
                DefaultTableModel dtm = (DefaultTableModel) customersInfoTable.getModel();
                dtm.setRowCount(0);
                if (customers != null) {
                    for (CustomerController customer : customers) {
                        Object[] data = {
                            customer.getId(),
                            customer.getName(),
                            customer.getMobile(),
                            customer.getAddress(),
                            customer.getPoints(),
                        };
                        dtm.addRow(data);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(AdminDashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_customersInfoTableHierarchyChanged

    private void searchCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerBtnActionPerformed
        // TODO add your handling code here:
        CustomerController cc = new CustomerController();
        try {
            CustomerController customer = cc.searchCustomer(cusMobileInput.getText());
            cusIDSearchResult.setText(customer.getId().toString());
            cusNameSearchResult.setText(customer.getName());
            cusAddressSearchResult.setText(customer.getAddress());
            cusPointsSearchResult.setText(customer.getPoints().toString());
        } catch (SQLException ex) {
            Logger.getLogger(CashierDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_searchCustomerBtnActionPerformed

    private void leftHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_leftHierarchyChanged
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            CashierController ac = new CashierController().getAccountInfo();
            cashName.setText(ac.getUsername());
            cashMobile.setText(ac.getMobile());
            cashAddress.setText(ac.getAddress());
            myName.setText(ac.getUsername());
            myMobile.setText(ac.getMobile());
            myAddress.setText(ac.getMobile());
        } catch (SQLException ex) {
            Logger.getLogger(CashierDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_leftHierarchyChanged

    private void orderDetailsTableHierarchyChanged(HierarchyEvent evt) {//GEN-FIRST:event_orderDetailsTableHierarchyChanged
        // TODO add your handling code here:
         if ((HierarchyEvent.SHOWING_CHANGED & evt.getChangeFlags()) != 0 && orderDetailsTable.isShowing()) {
            try {
                List<SalesController> sales = SalesController.viewSales();
                DefaultTableModel dtm = (DefaultTableModel) orderDetailsTable.getModel();
                dtm.setRowCount(0);
                if (sales != null) {
                    for (SalesController sale : sales) {
                        Object[] data = {
                            sale.getId(),
                            sale.getCusMobile(),
                            sale.getDate(),
                            sale.getDiscount(),
                            sale.getPoints(),
                            sale.getGrossTotal()
                        };
                        dtm.addRow(data);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(CashierDashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_orderDetailsTableHierarchyChanged

    private void customerMobileNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerMobileNoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_customerMobileNoKeyTyped

    private void customerMobileNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerMobileNoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_customerMobileNoKeyReleased

    private void verifyCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyCustomerBtnActionPerformed
        try {
            // TODO add your handling code here:
            CustomerController cc = new CustomerController();
            String cusMobileNo = customerMobileNo.getText();
            if(cc.customerExists(cusMobileNo)) {
                CustomerController ucc = new CustomerController().getCustomerPoints(cusMobileNo);
                totalPoints.setText(String.valueOf(ucc.getPoints()));
            } else {
                JOptionPane.showMessageDialog(null,"Customer not registered");
                customerMobileNo.setText("");
            }
        } catch (Exception ex) {
            Logger.getLogger(CashierDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_verifyCustomerBtnActionPerformed

    private void addPointsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPointsBtnActionPerformed
        try {
            // TODO add your handling code here:
            String cusMobileNo = customerMobileNo.getText();
            CustomerController cc = new CustomerController().getCustomerPoints(cusMobileNo);
            int pointsNeeded = Integer.parseInt(pointsToAdd.getText());
            int currPoints = cc.getPoints();
            if(pointsNeeded < currPoints) {
                int balancePoints = currPoints - pointsNeeded;
                if(cc.deductPoints(balancePoints, cusMobileNo)) {
                    points.setText(pointsToAdd.getText());
                } else {
                    JOptionPane.showMessageDialog(null,"Could not deduct points");
                }
            } else {
                JOptionPane.showMessageDialog(null,"Insufficient points");
            }
        } catch (Exception ex) {
            Logger.getLogger(CashierDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_addPointsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CashierDashboard().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CashierDashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
        public void switchPanels(JPanel panel){
            cashierLayeredPane.removeAll();
            cashierLayeredPane.add(panel);
            cashierLayeredPane.repaint();
            cashierLayeredPane.revalidate();
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addCusBtnPanel;
    private javax.swing.JPanel addCusBtnPanel1;
    private javax.swing.JButton addCustomerBtn;
    private javax.swing.JPanel addCustomerPanel;
    private javax.swing.JLabel addCustomerTitle;
    private javax.swing.JLabel addCustomerTitle1;
    private javax.swing.JPanel addCustomerTitlePanel;
    private javax.swing.JPanel addCustomerTitlePanel1;
    private javax.swing.JCheckBox addDiscountCheck;
    private javax.swing.JButton addItemBtn;
    private javax.swing.JButton addPointsBtn;
    private javax.swing.JPanel addPointsPanel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JPanel addressPanel;
    private javax.swing.JButton cancelChangesBtn;
    private javax.swing.JButton cancelPasswordChangeBtn;
    private javax.swing.JLabel cashAddress;
    private javax.swing.JLabel cashMobile;
    private javax.swing.JLabel cashName;
    private javax.swing.JLayeredPane cashierLayeredPane;
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JPanel checkoutBtnPanel;
    private javax.swing.JPanel checkoutPanel;
    private javax.swing.JPanel clearDetailsPanel;
    private javax.swing.JButton clearInfoBtn;
    private javax.swing.JPasswordField confPassword;
    private javax.swing.JLabel confPasswordLabel;
    private javax.swing.JPanel confPasswordPanel;
    private javax.swing.JPasswordField currPassword;
    private javax.swing.JLabel currPasswordLabel;
    private javax.swing.JPanel currentPasswordPanel;
    private javax.swing.JTextField cusAddress;
    private javax.swing.JLabel cusAddressSearchResult;
    private javax.swing.JLabel cusIDLabel;
    private javax.swing.JLabel cusIDSearchResult;
    private javax.swing.JTextField cusMobile;
    private javax.swing.JTextField cusMobileInput;
    private javax.swing.JLabel cusMobileLabel;
    private javax.swing.JPanel cusMobilePanel;
    private javax.swing.JLabel cusMobilleLabel;
    private javax.swing.JTextField cusName;
    private javax.swing.JLabel cusNameLabel;
    private javax.swing.JPanel cusNamePanel;
    private javax.swing.JLabel cusNameSearchResult;
    private javax.swing.JLabel cusPointsSearchResult;
    private javax.swing.JPanel cusSearchBtnPanel;
    private javax.swing.JPanel cusSearchInputPanel;
    private javax.swing.JPanel customerDetailsFormPanel;
    private javax.swing.JPanel customerDetailsFormPanel1;
    private javax.swing.JPanel customerDetailsPanel;
    private javax.swing.JTextField customerMobileNo;
    private javax.swing.JTable customersInfoTable;
    private javax.swing.JScrollPane customersInfoTablePanel;
    private javax.swing.JPanel customersTablePanel;
    private javax.swing.JPanel cutomerMobilePanel;
    private javax.swing.JLabel discount;
    private javax.swing.JPanel discountCheckPanel;
    private javax.swing.JLabel discountLabel;
    private javax.swing.JPanel discountPanel;
    private javax.swing.JLabel enterMobileNoLabel;
    private javax.swing.JLabel grossTotal;
    private javax.swing.JLabel grossTotalLabel;
    private javax.swing.JPanel grossTotalPanel;
    private javax.swing.JPanel itemsPanel;
    private javax.swing.JTable itemsTable;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel left;
    private javax.swing.JTextField myAddress;
    private javax.swing.JLabel myAddressLabel;
    private javax.swing.JPanel myAddressPanel;
    private javax.swing.JPanel myInfoActionPanel;
    private javax.swing.JTextField myMobile;
    private javax.swing.JLabel myMobileLabel;
    private javax.swing.JPanel myMobilePanel;
    private javax.swing.JTextField myName;
    private javax.swing.JLabel myNameLabel;
    private javax.swing.JPanel myNamePanel;
    private javax.swing.JPanel myPasswordActionPanel;
    private javax.swing.JPasswordField newPassword;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JPanel newPasswordPanel;
    private javax.swing.JTable orderDetailsTable;
    private javax.swing.JScrollPane orderDetailsTablePanel;
    private javax.swing.JPanel orderDetailsTitlePanel;
    private javax.swing.JLabel orderSecTitle;
    private javax.swing.JPanel orderSummaryPanel;
    private javax.swing.JLabel panelTitle;
    private javax.swing.JLabel points;
    private javax.swing.JLabel pointsLabel;
    private javax.swing.JPanel pointsPanel;
    private javax.swing.JTextField pointsToAdd;
    private javax.swing.JPanel right;
    private javax.swing.JPanel rightBottomPanel;
    private javax.swing.JPanel rightTopPanel;
    private javax.swing.JPanel salesPanel;
    private javax.swing.JPanel salesTablePanel;
    private javax.swing.JButton saveChangesBtn;
    private javax.swing.JButton saveNewPasswordBtn;
    private javax.swing.JButton searchCustomerBtn;
    private javax.swing.JPanel searchCustomerPanel;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JLabel subtotal;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JPanel subtotalPanel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JLabel totalPoints;
    private javax.swing.JLabel totalPointsLabel;
    private javax.swing.JPanel totalPointsPanel;
    private javax.swing.JPanel totalSummaryPanel;
    private javax.swing.JButton verifyCustomerBtn;
    private javax.swing.JPanel viewCustomersPanel;
    private javax.swing.JLabel viewCustomersTitle;
    private javax.swing.JPanel viewCustomersTitlePanel;
    private javax.swing.JPanel viewSalesPanel;
    // End of variables declaration//GEN-END:variables
}
