/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.views;

import javax.swing.JPanel;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author BiGDoGKD
 */
public class CashierDashboard extends javax.swing.JFrame {

    /**
     * Creates new form CashierDashboard
     */
    public CashierDashboard() {
        initComponents();
        setSize(900,520);
        setResizable(false);
        setVisible(true);
        
        super.setLocationRelativeTo(null);
        
        String[] a ={"Item1", "Item2", "Item3"};
        JComboBox c = new JComboBox(a);
        
        itemsTable.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(c));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cashierLayeredPane = new javax.swing.JLayeredPane();
        checkoutPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        panelTitle = new javax.swing.JLabel();
        itemsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemsTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        addItemBtn = new javax.swing.JButton();
        orderSummaryPanel = new javax.swing.JPanel();
        customerDetailsPanel = new javax.swing.JPanel();
        cutomerMobilePanel = new javax.swing.JPanel();
        cusMobilleLabel = new javax.swing.JLabel();
        cusMobileNo = new javax.swing.JTextField();
        totalPointsPanel = new javax.swing.JPanel();
        totalPointsLabel = new javax.swing.JLabel();
        totalPoints = new javax.swing.JLabel();
        addPointsPanel = new javax.swing.JPanel();
        pointsToAdd = new javax.swing.JTextField();
        addPointsBtn = new javax.swing.JButton();
        discountCheckPanel = new javax.swing.JPanel();
        addDiscountCheck = new javax.swing.JCheckBox();
        totalSummaryPanel = new javax.swing.JPanel();
        subtotalPanel = new javax.swing.JPanel();
        subtotal = new javax.swing.JLabel();
        subtotalLabel = new javax.swing.JLabel();
        discountPanel = new javax.swing.JPanel();
        discount = new javax.swing.JLabel();
        discountLabel = new javax.swing.JLabel();
        pointsPanel = new javax.swing.JPanel();
        points = new javax.swing.JLabel();
        pointsLabel = new javax.swing.JLabel();
        grossTotalPanel = new javax.swing.JPanel();
        grossTotal = new javax.swing.JLabel();
        grossTotalLabel = new javax.swing.JLabel();
        checkoutBtnPanel = new javax.swing.JPanel();
        checkoutBtn = new javax.swing.JButton();
        viewSalesPanel = new javax.swing.JPanel();
        salesPanel = new javax.swing.JPanel();
        orderDetailsTitlePanel = new javax.swing.JPanel();
        orderSecTitle = new javax.swing.JLabel();
        salesTablePanel = new javax.swing.JPanel();
        orderDetailsTablePanel = new javax.swing.JScrollPane();
        orderDetailsTable = new javax.swing.JTable();
        viewCustomersPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        addCustomerPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        searchCustomerPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        settingsPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cashierLayeredPane.setPreferredSize(new java.awt.Dimension(900, 520));
        cashierLayeredPane.setLayout(new java.awt.CardLayout());

        checkoutPanel.setLayout(new java.awt.BorderLayout());

        titlePanel.setPreferredSize(new java.awt.Dimension(900, 60));

        panelTitle.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        panelTitle.setText("Checkout");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(702, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        checkoutPanel.add(titlePanel, java.awt.BorderLayout.PAGE_START);

        itemsPanel.setPreferredSize(new java.awt.Dimension(550, 520));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(550, 350));

        itemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Item", "Quantity", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemsTable.setRowHeight(20);
        jScrollPane1.setViewportView(itemsTable);

        itemsPanel.add(jScrollPane1);

        jPanel1.setPreferredSize(new java.awt.Dimension(550, 100));

        addItemBtn.setText("Add Item");
        addItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 377, Short.MAX_VALUE)
                .addComponent(addItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(addItemBtn)
                .addGap(0, 75, Short.MAX_VALUE))
        );

        itemsPanel.add(jPanel1);

        checkoutPanel.add(itemsPanel, java.awt.BorderLayout.WEST);

        orderSummaryPanel.setPreferredSize(new java.awt.Dimension(350, 520));

        customerDetailsPanel.setPreferredSize(new java.awt.Dimension(350, 100));

        cutomerMobilePanel.setPreferredSize(new java.awt.Dimension(321, 30));

        cusMobilleLabel.setText("Customer Mobile No:");

        javax.swing.GroupLayout cutomerMobilePanelLayout = new javax.swing.GroupLayout(cutomerMobilePanel);
        cutomerMobilePanel.setLayout(cutomerMobilePanelLayout);
        cutomerMobilePanelLayout.setHorizontalGroup(
            cutomerMobilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cutomerMobilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cusMobilleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(cusMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cutomerMobilePanelLayout.setVerticalGroup(
            cutomerMobilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cutomerMobilePanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(cutomerMobilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cutomerMobilePanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(cusMobilleLabel))
                    .addComponent(cusMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        customerDetailsPanel.add(cutomerMobilePanel);

        totalPointsPanel.setPreferredSize(new java.awt.Dimension(321, 30));

        totalPointsLabel.setText("Total Points:");

        javax.swing.GroupLayout totalPointsPanelLayout = new javax.swing.GroupLayout(totalPointsPanel);
        totalPointsPanel.setLayout(totalPointsPanelLayout);
        totalPointsPanelLayout.setHorizontalGroup(
            totalPointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalPointsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalPointsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(totalPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        totalPointsPanelLayout.setVerticalGroup(
            totalPointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalPointsPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(totalPointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPointsLabel)
                    .addComponent(totalPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        customerDetailsPanel.add(totalPointsPanel);

        addPointsPanel.setPreferredSize(new java.awt.Dimension(321, 30));

        addPointsBtn.setText("Add Points");

        javax.swing.GroupLayout addPointsPanelLayout = new javax.swing.GroupLayout(addPointsPanel);
        addPointsPanel.setLayout(addPointsPanelLayout);
        addPointsPanelLayout.setHorizontalGroup(
            addPointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPointsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pointsToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(addPointsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        addPointsPanelLayout.setVerticalGroup(
            addPointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPointsPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(addPointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pointsToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPointsBtn))
                .addContainerGap())
        );

        customerDetailsPanel.add(addPointsPanel);

        orderSummaryPanel.add(customerDetailsPanel);

        discountCheckPanel.setPreferredSize(new java.awt.Dimension(350, 30));

        addDiscountCheck.setText("Add Discount");
        addDiscountCheck.setIconTextGap(10);
        addDiscountCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDiscountCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout discountCheckPanelLayout = new javax.swing.GroupLayout(discountCheckPanel);
        discountCheckPanel.setLayout(discountCheckPanelLayout);
        discountCheckPanelLayout.setHorizontalGroup(
            discountCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, discountCheckPanelLayout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(addDiscountCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        discountCheckPanelLayout.setVerticalGroup(
            discountCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(discountCheckPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(addDiscountCheck)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        orderSummaryPanel.add(discountCheckPanel);

        totalSummaryPanel.setPreferredSize(new java.awt.Dimension(350, 150));

        subtotalPanel.setPreferredSize(new java.awt.Dimension(321, 30));

        subtotalLabel.setText("Subtotal");

        javax.swing.GroupLayout subtotalPanelLayout = new javax.swing.GroupLayout(subtotalPanel);
        subtotalPanel.setLayout(subtotalPanelLayout);
        subtotalPanelLayout.setHorizontalGroup(
            subtotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subtotalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subtotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        subtotalPanelLayout.setVerticalGroup(
            subtotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subtotalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subtotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(subtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subtotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        totalSummaryPanel.add(subtotalPanel);

        discountPanel.setPreferredSize(new java.awt.Dimension(321, 30));

        discountLabel.setText("Discount");

        javax.swing.GroupLayout discountPanelLayout = new javax.swing.GroupLayout(discountPanel);
        discountPanel.setLayout(discountPanelLayout);
        discountPanelLayout.setHorizontalGroup(
            discountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(discountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(discountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        discountPanelLayout.setVerticalGroup(
            discountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(discountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(discountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(discountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(discount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3))
        );

        totalSummaryPanel.add(discountPanel);

        pointsPanel.setPreferredSize(new java.awt.Dimension(321, 30));

        pointsLabel.setText("Points");

        javax.swing.GroupLayout pointsPanelLayout = new javax.swing.GroupLayout(pointsPanel);
        pointsPanel.setLayout(pointsPanelLayout);
        pointsPanelLayout.setHorizontalGroup(
            pointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pointsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pointsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(points, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pointsPanelLayout.setVerticalGroup(
            pointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pointsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pointsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(points, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        totalSummaryPanel.add(pointsPanel);

        grossTotalPanel.setPreferredSize(new java.awt.Dimension(321, 30));

        grossTotalLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        grossTotalLabel.setText("Gross total");

        javax.swing.GroupLayout grossTotalPanelLayout = new javax.swing.GroupLayout(grossTotalPanel);
        grossTotalPanel.setLayout(grossTotalPanelLayout);
        grossTotalPanelLayout.setHorizontalGroup(
            grossTotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grossTotalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(grossTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(grossTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        grossTotalPanelLayout.setVerticalGroup(
            grossTotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grossTotalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(grossTotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(grossTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(grossTotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        totalSummaryPanel.add(grossTotalPanel);

        orderSummaryPanel.add(totalSummaryPanel);

        checkoutBtnPanel.setPreferredSize(new java.awt.Dimension(350, 50));

        checkoutBtn.setText("Checkout");

        javax.swing.GroupLayout checkoutBtnPanelLayout = new javax.swing.GroupLayout(checkoutBtnPanel);
        checkoutBtnPanel.setLayout(checkoutBtnPanelLayout);
        checkoutBtnPanelLayout.setHorizontalGroup(
            checkoutBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutBtnPanelLayout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(checkoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        checkoutBtnPanelLayout.setVerticalGroup(
            checkoutBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutBtnPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(checkoutBtn)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        orderSummaryPanel.add(checkoutBtnPanel);

        checkoutPanel.add(orderSummaryPanel, java.awt.BorderLayout.LINE_END);

        cashierLayeredPane.add(checkoutPanel, "card2");

        viewSalesPanel.setLayout(new java.awt.BorderLayout(10, 10));

        salesPanel.setPreferredSize(new java.awt.Dimension(900, 520));
        salesPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        orderDetailsTitlePanel.setAlignmentX(5.0F);
        orderDetailsTitlePanel.setAlignmentY(5.0F);
        orderDetailsTitlePanel.setPreferredSize(new java.awt.Dimension(900, 50));

        orderSecTitle.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        orderSecTitle.setText("Order Details");
        orderSecTitle.setAlignmentX(1.0F);

        javax.swing.GroupLayout orderDetailsTitlePanelLayout = new javax.swing.GroupLayout(orderDetailsTitlePanel);
        orderDetailsTitlePanel.setLayout(orderDetailsTitlePanelLayout);
        orderDetailsTitlePanelLayout.setHorizontalGroup(
            orderDetailsTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderDetailsTitlePanelLayout.createSequentialGroup()
                .addContainerGap(450, Short.MAX_VALUE)
                .addComponent(orderSecTitle)
                .addGap(361, 361, 361))
        );
        orderDetailsTitlePanelLayout.setVerticalGroup(
            orderDetailsTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderDetailsTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderSecTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        salesPanel.add(orderDetailsTitlePanel);

        salesTablePanel.setPreferredSize(new java.awt.Dimension(900, 410));

        orderDetailsTablePanel.setPreferredSize(new java.awt.Dimension(900, 403));

        orderDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order_ID", "Customer_Mobile", "Date", "Discount", "Points", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderDetailsTable.setIntercellSpacing(new java.awt.Dimension(2, 2));
        orderDetailsTable.setRowHeight(20);
        orderDetailsTable.setShowGrid(true);
        orderDetailsTablePanel.setViewportView(orderDetailsTable);
        if (orderDetailsTable.getColumnModel().getColumnCount() > 0) {
            orderDetailsTable.getColumnModel().getColumn(0).setPreferredWidth(50);
            orderDetailsTable.getColumnModel().getColumn(3).setPreferredWidth(60);
            orderDetailsTable.getColumnModel().getColumn(4).setPreferredWidth(60);
            orderDetailsTable.getColumnModel().getColumn(5).setPreferredWidth(60);
        }

        salesTablePanel.add(orderDetailsTablePanel);

        salesPanel.add(salesTablePanel);

        viewSalesPanel.add(salesPanel, java.awt.BorderLayout.WEST);

        cashierLayeredPane.add(viewSalesPanel, "card3");

        jLabel4.setText("View Customers");

        javax.swing.GroupLayout viewCustomersPanelLayout = new javax.swing.GroupLayout(viewCustomersPanel);
        viewCustomersPanel.setLayout(viewCustomersPanelLayout);
        viewCustomersPanelLayout.setHorizontalGroup(
            viewCustomersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewCustomersPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel4)
                .addContainerGap(765, Short.MAX_VALUE))
        );
        viewCustomersPanelLayout.setVerticalGroup(
            viewCustomersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewCustomersPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel4)
                .addContainerGap(439, Short.MAX_VALUE))
        );

        cashierLayeredPane.add(viewCustomersPanel, "card4");

        jLabel5.setText("Add Customer Panel");

        javax.swing.GroupLayout addCustomerPanelLayout = new javax.swing.GroupLayout(addCustomerPanel);
        addCustomerPanel.setLayout(addCustomerPanelLayout);
        addCustomerPanelLayout.setHorizontalGroup(
            addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCustomerPanelLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel5)
                .addContainerGap(715, Short.MAX_VALUE))
        );
        addCustomerPanelLayout.setVerticalGroup(
            addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCustomerPanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel5)
                .addContainerGap(403, Short.MAX_VALUE))
        );

        cashierLayeredPane.add(addCustomerPanel, "card5");

        jLabel6.setText("searchCustomerPanel");

        javax.swing.GroupLayout searchCustomerPanelLayout = new javax.swing.GroupLayout(searchCustomerPanel);
        searchCustomerPanel.setLayout(searchCustomerPanelLayout);
        searchCustomerPanelLayout.setHorizontalGroup(
            searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCustomerPanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel6)
                .addContainerGap(674, Short.MAX_VALUE))
        );
        searchCustomerPanelLayout.setVerticalGroup(
            searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCustomerPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel6)
                .addContainerGap(432, Short.MAX_VALUE))
        );

        cashierLayeredPane.add(searchCustomerPanel, "card6");

        jLabel7.setText("settingsPanel");

        javax.swing.GroupLayout settingsPanelLayout = new javax.swing.GroupLayout(settingsPanel);
        settingsPanel.setLayout(settingsPanelLayout);
        settingsPanelLayout.setHorizontalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel7)
                .addContainerGap(649, Short.MAX_VALUE))
        );
        settingsPanelLayout.setVerticalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel7)
                .addContainerGap(417, Short.MAX_VALUE))
        );

        cashierLayeredPane.add(settingsPanel, "card7");

        getContentPane().add(cashierLayeredPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        jMenu1.setText("Sales");

        jMenuItem1.setText("View Sales");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Chekout");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Customers");

        jMenuItem6.setText("View Customers");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Add Customer");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Search Customer");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Profile");

        jMenuItem4.setText("Settings");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Logout");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        switchPanels(viewSalesPanel);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        switchPanels(viewCustomersPanel);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        switchPanels(checkoutPanel);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        switchPanels(addCustomerPanel);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        switchPanels(searchCustomerPanel);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        switchPanels(settingsPanel);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void addDiscountCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDiscountCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDiscountCheckActionPerformed

    private void addItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)itemsTable.getModel();
        model.addRow(new Object[]{});
    }//GEN-LAST:event_addItemBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierDashboard().setVisible(true);
            }
        });
    }
    
        public void switchPanels(JPanel panel){
            cashierLayeredPane.removeAll();
            cashierLayeredPane.add(panel);
            cashierLayeredPane.repaint();
            cashierLayeredPane.revalidate();
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addCustomerPanel;
    private javax.swing.JCheckBox addDiscountCheck;
    private javax.swing.JButton addItemBtn;
    private javax.swing.JButton addPointsBtn;
    private javax.swing.JPanel addPointsPanel;
    private javax.swing.JLayeredPane cashierLayeredPane;
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JPanel checkoutBtnPanel;
    private javax.swing.JPanel checkoutPanel;
    private javax.swing.JTextField cusMobileNo;
    private javax.swing.JLabel cusMobilleLabel;
    private javax.swing.JPanel customerDetailsPanel;
    private javax.swing.JPanel cutomerMobilePanel;
    private javax.swing.JLabel discount;
    private javax.swing.JPanel discountCheckPanel;
    private javax.swing.JLabel discountLabel;
    private javax.swing.JPanel discountPanel;
    private javax.swing.JLabel grossTotal;
    private javax.swing.JLabel grossTotalLabel;
    private javax.swing.JPanel grossTotalPanel;
    private javax.swing.JPanel itemsPanel;
    private javax.swing.JTable itemsTable;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderDetailsTable;
    private javax.swing.JScrollPane orderDetailsTablePanel;
    private javax.swing.JPanel orderDetailsTitlePanel;
    private javax.swing.JLabel orderSecTitle;
    private javax.swing.JPanel orderSummaryPanel;
    private javax.swing.JLabel panelTitle;
    private javax.swing.JLabel points;
    private javax.swing.JLabel pointsLabel;
    private javax.swing.JPanel pointsPanel;
    private javax.swing.JTextField pointsToAdd;
    private javax.swing.JPanel salesPanel;
    private javax.swing.JPanel salesTablePanel;
    private javax.swing.JPanel searchCustomerPanel;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JLabel subtotal;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JPanel subtotalPanel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JLabel totalPoints;
    private javax.swing.JLabel totalPointsLabel;
    private javax.swing.JPanel totalPointsPanel;
    private javax.swing.JPanel totalSummaryPanel;
    private javax.swing.JPanel viewCustomersPanel;
    private javax.swing.JPanel viewSalesPanel;
    // End of variables declaration//GEN-END:variables
}
